// <auto-generated />
using System;
using DOTNET_hocmienphi.repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DOTNET_hocmienphi.repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260812135658_SendAdvertiseUserField")]
    partial class SendAdvertiseUserField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.ApplyRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CvLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("RejectReason")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ApplyRequests");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.ApplyRequestCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplyRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ApplyRequestId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ApplyRequestCategories");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MentorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StarTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MentorId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Mentor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentPosition")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Mentors");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.MentorCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MentorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("MentorId");

                    b.ToTable("MentorCategories");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.MentorFreetime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DateOfWeek")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MentorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MentorId");

                    b.ToTable("MentorFreetimes");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSendAdvertise")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SendDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f262307-fbf1-453b-9b29-100aca76d059"),
                            Age = "10",
                            Email = "Email0@gmail.com",
                            FirstName = "FirstName0",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName0",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("e244bac3-6eb7-4bfd-89ae-570ce3217845"),
                            Age = "10",
                            Email = "Email1@gmail.com",
                            FirstName = "FirstName1",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName1",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("6979b505-227b-48c2-a115-822365f5dffb"),
                            Age = "10",
                            Email = "Email2@gmail.com",
                            FirstName = "FirstName2",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName2",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("42948243-eb81-4dba-a8d5-6ab5c696da32"),
                            Age = "10",
                            Email = "Email3@gmail.com",
                            FirstName = "FirstName3",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName3",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("a311b2ff-868a-4aa7-870a-16edded16912"),
                            Age = "10",
                            Email = "Email4@gmail.com",
                            FirstName = "FirstName4",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName4",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("afc52edb-ac6c-488d-9e49-67828fbd8e0d"),
                            Age = "10",
                            Email = "Email5@gmail.com",
                            FirstName = "FirstName5",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName5",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("daafd776-7983-48e6-98cb-4fea510c7a4e"),
                            Age = "10",
                            Email = "Email6@gmail.com",
                            FirstName = "FirstName6",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName6",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("6f80fa2d-2243-4d15-a267-aaa43bc52565"),
                            Age = "10",
                            Email = "Email7@gmail.com",
                            FirstName = "FirstName7",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName7",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("d7626bd4-fab5-409f-900d-03c940b6dda1"),
                            Age = "10",
                            Email = "Email8@gmail.com",
                            FirstName = "FirstName8",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName8",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("be53041b-0d9a-43c9-9594-f41459ad9c66"),
                            Age = "10",
                            Email = "Email9@gmail.com",
                            FirstName = "FirstName9",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName9",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("a4f2ba39-993c-46d9-b684-7c49f72502ea"),
                            Age = "10",
                            Email = "Email10@gmail.com",
                            FirstName = "FirstName10",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName10",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("c61baabb-77df-47f4-9ccb-f40d7462036e"),
                            Age = "10",
                            Email = "Email11@gmail.com",
                            FirstName = "FirstName11",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName11",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("bec7cde7-4443-4fde-9bf7-b920d907177d"),
                            Age = "10",
                            Email = "Email12@gmail.com",
                            FirstName = "FirstName12",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName12",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("61428124-8ee9-4e9d-820d-f9ef084c4d00"),
                            Age = "10",
                            Email = "Email13@gmail.com",
                            FirstName = "FirstName13",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName13",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("de3405e3-258a-4780-9817-e11a4e6d1950"),
                            Age = "10",
                            Email = "Email14@gmail.com",
                            FirstName = "FirstName14",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName14",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("71e57f0c-4fd9-4c81-a470-182ae45404ce"),
                            Age = "10",
                            Email = "Email15@gmail.com",
                            FirstName = "FirstName15",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName15",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("2249c8c9-cc6c-4807-9f9e-96fd34e60a13"),
                            Age = "10",
                            Email = "Email16@gmail.com",
                            FirstName = "FirstName16",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName16",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("d4208a40-a42f-4e42-b94c-d98eaf27170b"),
                            Age = "10",
                            Email = "Email17@gmail.com",
                            FirstName = "FirstName17",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName17",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("8512bbd7-81cd-4490-b860-8cd58d219d36"),
                            Age = "10",
                            Email = "Email18@gmail.com",
                            FirstName = "FirstName18",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName18",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("17721273-ba05-4d0d-b156-1683ac752476"),
                            Age = "10",
                            Email = "Email19@gmail.com",
                            FirstName = "FirstName19",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName19",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("79210da7-edca-42a1-9134-298b6c0fbbbe"),
                            Age = "10",
                            Email = "Email20@gmail.com",
                            FirstName = "FirstName20",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName20",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("a527f2cc-2552-4e36-8524-f9944f3a234c"),
                            Age = "10",
                            Email = "Email21@gmail.com",
                            FirstName = "FirstName21",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName21",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("25ffe6f8-7daf-4495-ae36-4afe99500796"),
                            Age = "10",
                            Email = "Email22@gmail.com",
                            FirstName = "FirstName22",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName22",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("72dfcea5-df84-4e7f-9eca-cdf9ace9e00b"),
                            Age = "10",
                            Email = "Email23@gmail.com",
                            FirstName = "FirstName23",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName23",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("9162aa76-6439-446f-b528-63b014e0ee72"),
                            Age = "10",
                            Email = "Email24@gmail.com",
                            FirstName = "FirstName24",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName24",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("80879841-0ea4-4a2d-98e1-35f213e173f9"),
                            Age = "10",
                            Email = "Email25@gmail.com",
                            FirstName = "FirstName25",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName25",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("1c413f53-40b3-4971-a806-78d720d347b8"),
                            Age = "10",
                            Email = "Email26@gmail.com",
                            FirstName = "FirstName26",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName26",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("7e33825a-3db3-4cef-9212-f063a87cf125"),
                            Age = "10",
                            Email = "Email27@gmail.com",
                            FirstName = "FirstName27",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName27",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("47c0c8f8-48ae-4b61-bd3a-f204063aa913"),
                            Age = "10",
                            Email = "Email28@gmail.com",
                            FirstName = "FirstName28",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName28",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("dcb71981-c5b4-42bd-83ce-b7d94bea79f6"),
                            Age = "10",
                            Email = "Email29@gmail.com",
                            FirstName = "FirstName29",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName29",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("9ab2c3f7-6b4e-4701-97c1-36ae2279d10e"),
                            Age = "10",
                            Email = "Email30@gmail.com",
                            FirstName = "FirstName30",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName30",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("a70df33a-7f89-4bfb-a627-fdb856ed6d1e"),
                            Age = "10",
                            Email = "Email31@gmail.com",
                            FirstName = "FirstName31",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName31",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("b3a540b9-1c39-4015-86be-4c1bb4c26c6f"),
                            Age = "10",
                            Email = "Email32@gmail.com",
                            FirstName = "FirstName32",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName32",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("6b707b46-3a7d-461f-be4b-a8551757bc64"),
                            Age = "10",
                            Email = "Email33@gmail.com",
                            FirstName = "FirstName33",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName33",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("874dc8f3-2f47-46a8-a8fe-3f9f9aebeb09"),
                            Age = "10",
                            Email = "Email34@gmail.com",
                            FirstName = "FirstName34",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName34",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("bafd418a-ab5b-4679-87d5-f0115bb3e6cd"),
                            Age = "10",
                            Email = "Email35@gmail.com",
                            FirstName = "FirstName35",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName35",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("2cdcee96-04f8-4ecf-b95a-9d1307d45c11"),
                            Age = "10",
                            Email = "Email36@gmail.com",
                            FirstName = "FirstName36",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName36",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("beb8b89f-a538-4d96-b10e-207f987bfa59"),
                            Age = "10",
                            Email = "Email37@gmail.com",
                            FirstName = "FirstName37",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName37",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("e4942f77-705f-4732-99a2-a4b608bc814b"),
                            Age = "10",
                            Email = "Email38@gmail.com",
                            FirstName = "FirstName38",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName38",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("e39653c9-9e84-4436-83d1-ab2d9aa54de7"),
                            Age = "10",
                            Email = "Email39@gmail.com",
                            FirstName = "FirstName39",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName39",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("8fd2780c-09a3-43f6-aba3-ae00e87becd4"),
                            Age = "10",
                            Email = "Email40@gmail.com",
                            FirstName = "FirstName40",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName40",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("b13fccae-54a6-4081-a734-dcefe337f135"),
                            Age = "10",
                            Email = "Email41@gmail.com",
                            FirstName = "FirstName41",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName41",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("887f96f4-8685-4222-a78e-fb49b1e56770"),
                            Age = "10",
                            Email = "Email42@gmail.com",
                            FirstName = "FirstName42",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName42",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("20086997-6cd6-4720-8c11-6285fee0af04"),
                            Age = "10",
                            Email = "Email43@gmail.com",
                            FirstName = "FirstName43",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName43",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("34501c85-767b-4724-bd87-6a7130f308d5"),
                            Age = "10",
                            Email = "Email44@gmail.com",
                            FirstName = "FirstName44",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName44",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("aeef1884-3a5e-450e-84be-deb4a920d52e"),
                            Age = "10",
                            Email = "Email45@gmail.com",
                            FirstName = "FirstName45",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName45",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("f7c0232d-1555-42aa-b7eb-5bc164f975c1"),
                            Age = "10",
                            Email = "Email46@gmail.com",
                            FirstName = "FirstName46",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName46",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("583ea401-7517-4e13-9c98-bb03650d5b0a"),
                            Age = "10",
                            Email = "Email47@gmail.com",
                            FirstName = "FirstName47",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName47",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("a2bcaa76-3e66-491f-ac6a-f8151498f691"),
                            Age = "10",
                            Email = "Email48@gmail.com",
                            FirstName = "FirstName48",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName48",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("13b9e8e5-78c0-46cb-a91a-3638f8eb0a30"),
                            Age = "10",
                            Email = "Email49@gmail.com",
                            FirstName = "FirstName49",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName49",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("b2d3a7dd-80d9-4796-bec4-a83d785ecf8c"),
                            Age = "10",
                            Email = "Email50@gmail.com",
                            FirstName = "FirstName50",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName50",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("d840a8c8-9657-47c4-b926-900787800768"),
                            Age = "10",
                            Email = "Email51@gmail.com",
                            FirstName = "FirstName51",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName51",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("adc239f3-b1c7-4878-ac4c-c4840638557e"),
                            Age = "10",
                            Email = "Email52@gmail.com",
                            FirstName = "FirstName52",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName52",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("ca075071-77a5-47e4-b07e-aa058948c813"),
                            Age = "10",
                            Email = "Email53@gmail.com",
                            FirstName = "FirstName53",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName53",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("9f6a4870-b7da-4152-a38d-d143daf1817c"),
                            Age = "10",
                            Email = "Email54@gmail.com",
                            FirstName = "FirstName54",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName54",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("bdf936ce-5735-4c98-85e6-82895f3f7779"),
                            Age = "10",
                            Email = "Email55@gmail.com",
                            FirstName = "FirstName55",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName55",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("66fce547-b64c-4b48-b418-340400738a89"),
                            Age = "10",
                            Email = "Email56@gmail.com",
                            FirstName = "FirstName56",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName56",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("a0837924-272d-4cc0-ad33-7d8af4e2efad"),
                            Age = "10",
                            Email = "Email57@gmail.com",
                            FirstName = "FirstName57",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName57",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0cc55b84-44cf-41f0-8a41-16f45c3e500b"),
                            Age = "10",
                            Email = "Email58@gmail.com",
                            FirstName = "FirstName58",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName58",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("cad72368-971d-4a55-b3bc-85e99688b116"),
                            Age = "10",
                            Email = "Email59@gmail.com",
                            FirstName = "FirstName59",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName59",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("e665bd5e-1639-41d3-a463-8f1b04d17383"),
                            Age = "10",
                            Email = "Email60@gmail.com",
                            FirstName = "FirstName60",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName60",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("64cd25f8-cd38-4800-91a1-c434f83afc33"),
                            Age = "10",
                            Email = "Email61@gmail.com",
                            FirstName = "FirstName61",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName61",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("d3a8da86-055f-4cc3-a6a7-e1b354c3f584"),
                            Age = "10",
                            Email = "Email62@gmail.com",
                            FirstName = "FirstName62",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName62",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("552f0904-def9-4c0e-a4f3-c25514f803de"),
                            Age = "10",
                            Email = "Email63@gmail.com",
                            FirstName = "FirstName63",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName63",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("c321c71b-4264-4390-abf7-93632707847d"),
                            Age = "10",
                            Email = "Email64@gmail.com",
                            FirstName = "FirstName64",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName64",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("08a7be4c-88d9-43f2-b076-0ba8768ae285"),
                            Age = "10",
                            Email = "Email65@gmail.com",
                            FirstName = "FirstName65",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName65",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("621643d1-8e1a-44b6-9763-c695ff071092"),
                            Age = "10",
                            Email = "Email66@gmail.com",
                            FirstName = "FirstName66",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName66",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("8811ab27-4981-4e37-96cb-320265612d28"),
                            Age = "10",
                            Email = "Email67@gmail.com",
                            FirstName = "FirstName67",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName67",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("169e006c-679c-4a5a-8e38-61983f5ba224"),
                            Age = "10",
                            Email = "Email68@gmail.com",
                            FirstName = "FirstName68",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName68",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("1df636dc-7d3f-40ae-857b-fdbde5d97cce"),
                            Age = "10",
                            Email = "Email69@gmail.com",
                            FirstName = "FirstName69",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName69",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("da50eb95-dd10-4dd3-be90-ddeb01f8f238"),
                            Age = "10",
                            Email = "Email70@gmail.com",
                            FirstName = "FirstName70",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName70",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("71c7b702-1b7e-4264-9d42-83b3e7294ac4"),
                            Age = "10",
                            Email = "Email71@gmail.com",
                            FirstName = "FirstName71",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName71",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0714a6e4-abe7-4cf8-b8fc-c821eb5738de"),
                            Age = "10",
                            Email = "Email72@gmail.com",
                            FirstName = "FirstName72",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName72",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("5d091e07-6ccf-40dc-938b-461edb9458c0"),
                            Age = "10",
                            Email = "Email73@gmail.com",
                            FirstName = "FirstName73",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName73",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("18476744-f304-4bbb-a288-2efea5203959"),
                            Age = "10",
                            Email = "Email74@gmail.com",
                            FirstName = "FirstName74",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName74",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("3efcfec0-ade5-49a2-92a2-2cd5bfe5a41a"),
                            Age = "10",
                            Email = "Email75@gmail.com",
                            FirstName = "FirstName75",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName75",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("7a784c9c-8ab1-4744-80f0-ec217608103f"),
                            Age = "10",
                            Email = "Email76@gmail.com",
                            FirstName = "FirstName76",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName76",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("feaad1c7-5e5f-4692-b28c-d4cf3916edf0"),
                            Age = "10",
                            Email = "Email77@gmail.com",
                            FirstName = "FirstName77",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName77",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("da9e2d9c-b3d8-4123-a8fe-d70019c66c9d"),
                            Age = "10",
                            Email = "Email78@gmail.com",
                            FirstName = "FirstName78",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName78",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0c85ce20-cfa4-4110-b5b5-7da078a075b4"),
                            Age = "10",
                            Email = "Email79@gmail.com",
                            FirstName = "FirstName79",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName79",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("e4fe6fd0-3413-4cca-b2f6-918621eb9f03"),
                            Age = "10",
                            Email = "Email80@gmail.com",
                            FirstName = "FirstName80",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName80",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("d568a3b2-0712-4061-8bbf-6c65edba8646"),
                            Age = "10",
                            Email = "Email81@gmail.com",
                            FirstName = "FirstName81",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName81",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("f4d1a23c-659a-49c5-8fa2-a7347798ede7"),
                            Age = "10",
                            Email = "Email82@gmail.com",
                            FirstName = "FirstName82",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName82",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("4b699c4c-0040-49eb-b9be-b05bc72dee81"),
                            Age = "10",
                            Email = "Email83@gmail.com",
                            FirstName = "FirstName83",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName83",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("cccee40a-9800-4d3b-b41e-80d61353fbdd"),
                            Age = "10",
                            Email = "Email84@gmail.com",
                            FirstName = "FirstName84",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName84",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("06b94509-843d-4b15-982f-0f367668b71e"),
                            Age = "10",
                            Email = "Email85@gmail.com",
                            FirstName = "FirstName85",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName85",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("80802941-7225-4a70-b58e-e14d24dc5d05"),
                            Age = "10",
                            Email = "Email86@gmail.com",
                            FirstName = "FirstName86",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName86",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("db0b6b2d-963d-45aa-b290-f5232b3407b3"),
                            Age = "10",
                            Email = "Email87@gmail.com",
                            FirstName = "FirstName87",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName87",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("eec0192b-d079-4b54-aacb-b6c2a9f3518f"),
                            Age = "10",
                            Email = "Email88@gmail.com",
                            FirstName = "FirstName88",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName88",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("b684f5f6-77cb-4409-b900-8fe0ff2a7ee2"),
                            Age = "10",
                            Email = "Email89@gmail.com",
                            FirstName = "FirstName89",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName89",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("ca409d96-24d9-431a-b433-a27b2578378f"),
                            Age = "10",
                            Email = "Email90@gmail.com",
                            FirstName = "FirstName90",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName90",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("b70b675a-19d9-4de9-b8a1-3668abf271bc"),
                            Age = "10",
                            Email = "Email91@gmail.com",
                            FirstName = "FirstName91",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName91",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00d753d1-f53e-4cf4-9d18-81c63fc08092"),
                            Age = "10",
                            Email = "Email92@gmail.com",
                            FirstName = "FirstName92",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName92",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("1e29333d-4f69-498f-9005-0e703729ac1a"),
                            Age = "10",
                            Email = "Email93@gmail.com",
                            FirstName = "FirstName93",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName93",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("6a77cb91-6d5e-4d14-bfa9-ab656f9b292d"),
                            Age = "10",
                            Email = "Email94@gmail.com",
                            FirstName = "FirstName94",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName94",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("98255944-f6c8-4dea-86d6-7bb47c8af9c5"),
                            Age = "10",
                            Email = "Email95@gmail.com",
                            FirstName = "FirstName95",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName95",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("2cf8354a-3612-4c0b-9a61-60d3846bb99a"),
                            Age = "10",
                            Email = "Email96@gmail.com",
                            FirstName = "FirstName96",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName96",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0be30c2d-7cdb-465d-9402-4ad645b7ab9e"),
                            Age = "10",
                            Email = "Email97@gmail.com",
                            FirstName = "FirstName97",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName97",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("87a697f9-4d59-4239-a5cb-7d99c4f9bc85"),
                            Age = "10",
                            Email = "Email98@gmail.com",
                            FirstName = "FirstName98",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName98",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("d07257db-952b-4983-8ca6-b0e0adae2f15"),
                            Age = "10",
                            Email = "Email99@gmail.com",
                            FirstName = "FirstName99",
                            IsDeleted = false,
                            IsSendAdvertise = false,
                            LastName = "LastName99",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.ApplyRequest", b =>
                {
                    b.HasOne("DOTNET_hocmienphi.repository.entity.User", "User")
                        .WithMany("ApplyRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.ApplyRequestCategory", b =>
                {
                    b.HasOne("DOTNET_hocmienphi.repository.entity.ApplyRequest", "ApplyRequest")
                        .WithMany("ApplyRequestCategories")
                        .HasForeignKey("ApplyRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DOTNET_hocmienphi.repository.entity.Category", "Category")
                        .WithMany("ApplyRequestCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplyRequest");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Booking", b =>
                {
                    b.HasOne("DOTNET_hocmienphi.repository.entity.Mentor", "Mentor")
                        .WithMany("Bookings")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DOTNET_hocmienphi.repository.entity.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mentor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Category", b =>
                {
                    b.HasOne("DOTNET_hocmienphi.repository.entity.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Mentor", b =>
                {
                    b.HasOne("DOTNET_hocmienphi.repository.entity.User", "User")
                        .WithOne("Mentor")
                        .HasForeignKey("DOTNET_hocmienphi.repository.entity.Mentor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.MentorCategory", b =>
                {
                    b.HasOne("DOTNET_hocmienphi.repository.entity.Category", "Category")
                        .WithMany("MentorCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DOTNET_hocmienphi.repository.entity.Mentor", "Mentor")
                        .WithMany("MentorCategories")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.MentorFreetime", b =>
                {
                    b.HasOne("DOTNET_hocmienphi.repository.entity.Mentor", "Mentor")
                        .WithMany("MentorFreetimes")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.ApplyRequest", b =>
                {
                    b.Navigation("ApplyRequestCategories");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Category", b =>
                {
                    b.Navigation("ApplyRequestCategories");

                    b.Navigation("Children");

                    b.Navigation("MentorCategories");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Mentor", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("MentorCategories");

                    b.Navigation("MentorFreetimes");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.User", b =>
                {
                    b.Navigation("ApplyRequests");

                    b.Navigation("Bookings");

                    b.Navigation("Mentor");
                });
#pragma warning restore 612, 618
        }
    }
}
