// <auto-generated />
using System;
using DOTNET_hocmienphi.repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DOTNET_hocmienphi.repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260812151206_muahahha")]
    partial class muahahha
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.ApplyRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CvLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("RejectReason")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ApplyRequests");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.ApplyRequestCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplyRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ApplyRequestId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ApplyRequestCategories");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MentorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StarTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MentorId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Mentor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentPosition")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Mentors");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.MentorCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MentorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("MentorId");

                    b.ToTable("MentorCategories");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.MentorFreetime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DateOfWeek")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MentorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MentorId");

                    b.ToTable("MentorFreetimes");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("SendDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("69211a23-8ed0-4fdf-9618-c5c60b486546"),
                            Age = "10",
                            Email = "Email0@gmail.com",
                            FirstName = "FirstName0",
                            IsDeleted = false,
                            LastName = "LastName0",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("d8063a74-ca95-4106-be33-87c707703057"),
                            Age = "10",
                            Email = "Email1@gmail.com",
                            FirstName = "FirstName1",
                            IsDeleted = false,
                            LastName = "LastName1",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("dd46fcfb-d126-4fa9-83a0-2d16be72a5c5"),
                            Age = "10",
                            Email = "Email2@gmail.com",
                            FirstName = "FirstName2",
                            IsDeleted = false,
                            LastName = "LastName2",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("6864d98b-5fc8-4395-8305-23fcbd0718e3"),
                            Age = "10",
                            Email = "Email3@gmail.com",
                            FirstName = "FirstName3",
                            IsDeleted = false,
                            LastName = "LastName3",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("382573d3-eedb-46c7-9856-a633818ef08b"),
                            Age = "10",
                            Email = "Email4@gmail.com",
                            FirstName = "FirstName4",
                            IsDeleted = false,
                            LastName = "LastName4",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("a0ebc528-15ea-4b46-a60e-a6f6949f407a"),
                            Age = "10",
                            Email = "Email5@gmail.com",
                            FirstName = "FirstName5",
                            IsDeleted = false,
                            LastName = "LastName5",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("349dcf24-60a7-47f4-b1d4-9b5c882fec6f"),
                            Age = "10",
                            Email = "Email6@gmail.com",
                            FirstName = "FirstName6",
                            IsDeleted = false,
                            LastName = "LastName6",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("2127210b-a00a-4fc2-8c38-25a231748266"),
                            Age = "10",
                            Email = "Email7@gmail.com",
                            FirstName = "FirstName7",
                            IsDeleted = false,
                            LastName = "LastName7",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("73215213-b272-48ad-a1f3-486aedd2561a"),
                            Age = "10",
                            Email = "Email8@gmail.com",
                            FirstName = "FirstName8",
                            IsDeleted = false,
                            LastName = "LastName8",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("d2ec49bd-f61b-469a-8f73-d9c29547d784"),
                            Age = "10",
                            Email = "Email9@gmail.com",
                            FirstName = "FirstName9",
                            IsDeleted = false,
                            LastName = "LastName9",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("b0a88f99-f078-420d-870f-7859e9baae19"),
                            Age = "10",
                            Email = "Email10@gmail.com",
                            FirstName = "FirstName10",
                            IsDeleted = false,
                            LastName = "LastName10",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("ef340ead-fe45-4215-bcd8-104ad23b7042"),
                            Age = "10",
                            Email = "Email11@gmail.com",
                            FirstName = "FirstName11",
                            IsDeleted = false,
                            LastName = "LastName11",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("24d6008e-8748-4c1f-9143-c3e0f66e7977"),
                            Age = "10",
                            Email = "Email12@gmail.com",
                            FirstName = "FirstName12",
                            IsDeleted = false,
                            LastName = "LastName12",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("edfc5505-3719-4ada-98fa-81aacad55227"),
                            Age = "10",
                            Email = "Email13@gmail.com",
                            FirstName = "FirstName13",
                            IsDeleted = false,
                            LastName = "LastName13",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("05b4b294-854b-4ea2-b6a7-4a4ffdf147eb"),
                            Age = "10",
                            Email = "Email14@gmail.com",
                            FirstName = "FirstName14",
                            IsDeleted = false,
                            LastName = "LastName14",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("be3ca68b-5989-4274-b639-062f030333f6"),
                            Age = "10",
                            Email = "Email15@gmail.com",
                            FirstName = "FirstName15",
                            IsDeleted = false,
                            LastName = "LastName15",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("f8503dfa-ba00-48d7-8cdc-88e8f0d30b2f"),
                            Age = "10",
                            Email = "Email16@gmail.com",
                            FirstName = "FirstName16",
                            IsDeleted = false,
                            LastName = "LastName16",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("96e9f7d7-fbc4-49bf-8916-1d2da5646bd4"),
                            Age = "10",
                            Email = "Email17@gmail.com",
                            FirstName = "FirstName17",
                            IsDeleted = false,
                            LastName = "LastName17",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("6f2fc807-063c-4946-859b-a41044d1aada"),
                            Age = "10",
                            Email = "Email18@gmail.com",
                            FirstName = "FirstName18",
                            IsDeleted = false,
                            LastName = "LastName18",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("95863ca0-ed86-45b1-a99b-43b821fe3260"),
                            Age = "10",
                            Email = "Email19@gmail.com",
                            FirstName = "FirstName19",
                            IsDeleted = false,
                            LastName = "LastName19",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("072efd6b-f5be-4ae3-992b-f836b5d12221"),
                            Age = "10",
                            Email = "Email20@gmail.com",
                            FirstName = "FirstName20",
                            IsDeleted = false,
                            LastName = "LastName20",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("30829326-5aa4-4a94-aaf3-af6546467df1"),
                            Age = "10",
                            Email = "Email21@gmail.com",
                            FirstName = "FirstName21",
                            IsDeleted = false,
                            LastName = "LastName21",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("b5cc6016-eee4-400c-be6b-a7bd98ce3e1a"),
                            Age = "10",
                            Email = "Email22@gmail.com",
                            FirstName = "FirstName22",
                            IsDeleted = false,
                            LastName = "LastName22",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("042203ba-9018-44c7-b3b1-e0d2094c6cfa"),
                            Age = "10",
                            Email = "Email23@gmail.com",
                            FirstName = "FirstName23",
                            IsDeleted = false,
                            LastName = "LastName23",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("26c4ad96-855f-4550-8c73-d773fda6a57c"),
                            Age = "10",
                            Email = "Email24@gmail.com",
                            FirstName = "FirstName24",
                            IsDeleted = false,
                            LastName = "LastName24",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("3cc8798a-1667-4c44-876f-fe3e54ddacc1"),
                            Age = "10",
                            Email = "Email25@gmail.com",
                            FirstName = "FirstName25",
                            IsDeleted = false,
                            LastName = "LastName25",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("72476895-ef20-432e-9209-51c6032c0f33"),
                            Age = "10",
                            Email = "Email26@gmail.com",
                            FirstName = "FirstName26",
                            IsDeleted = false,
                            LastName = "LastName26",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("9accaed1-f459-427f-8e9b-2e0db21b161f"),
                            Age = "10",
                            Email = "Email27@gmail.com",
                            FirstName = "FirstName27",
                            IsDeleted = false,
                            LastName = "LastName27",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("070c36fc-54ce-4457-95dd-72c59dc60445"),
                            Age = "10",
                            Email = "Email28@gmail.com",
                            FirstName = "FirstName28",
                            IsDeleted = false,
                            LastName = "LastName28",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("e373cf44-46aa-4541-b3be-210651c60e5a"),
                            Age = "10",
                            Email = "Email29@gmail.com",
                            FirstName = "FirstName29",
                            IsDeleted = false,
                            LastName = "LastName29",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("8cb1dee2-23ca-4470-aae4-d66c752bfbf5"),
                            Age = "10",
                            Email = "Email30@gmail.com",
                            FirstName = "FirstName30",
                            IsDeleted = false,
                            LastName = "LastName30",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("134d6c74-a3bc-46cf-ac57-fce337aa30ed"),
                            Age = "10",
                            Email = "Email31@gmail.com",
                            FirstName = "FirstName31",
                            IsDeleted = false,
                            LastName = "LastName31",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("4a1eed2e-9273-4c2f-96a4-9f01eea8d6dd"),
                            Age = "10",
                            Email = "Email32@gmail.com",
                            FirstName = "FirstName32",
                            IsDeleted = false,
                            LastName = "LastName32",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("bd4283f1-898a-42a7-bcb0-fd1cb6115811"),
                            Age = "10",
                            Email = "Email33@gmail.com",
                            FirstName = "FirstName33",
                            IsDeleted = false,
                            LastName = "LastName33",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("8a46df0e-a9c5-4e44-b1f5-a961265967d7"),
                            Age = "10",
                            Email = "Email34@gmail.com",
                            FirstName = "FirstName34",
                            IsDeleted = false,
                            LastName = "LastName34",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("157d1b73-27af-4899-b730-fe9c424a83b2"),
                            Age = "10",
                            Email = "Email35@gmail.com",
                            FirstName = "FirstName35",
                            IsDeleted = false,
                            LastName = "LastName35",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("6b40573d-a9cd-4358-81ac-1f9af2e93476"),
                            Age = "10",
                            Email = "Email36@gmail.com",
                            FirstName = "FirstName36",
                            IsDeleted = false,
                            LastName = "LastName36",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("4f4995fc-358f-4e24-9597-f93c564b02ea"),
                            Age = "10",
                            Email = "Email37@gmail.com",
                            FirstName = "FirstName37",
                            IsDeleted = false,
                            LastName = "LastName37",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("e7e7c400-9228-40e9-8aa8-104a7387582d"),
                            Age = "10",
                            Email = "Email38@gmail.com",
                            FirstName = "FirstName38",
                            IsDeleted = false,
                            LastName = "LastName38",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("0a7aaa51-1033-489c-a169-492f8c80f3ba"),
                            Age = "10",
                            Email = "Email39@gmail.com",
                            FirstName = "FirstName39",
                            IsDeleted = false,
                            LastName = "LastName39",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("54cd683c-6076-4a36-b892-b7c4d91ffe80"),
                            Age = "10",
                            Email = "Email40@gmail.com",
                            FirstName = "FirstName40",
                            IsDeleted = false,
                            LastName = "LastName40",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("f1e206fd-a841-4172-9b59-aad6663da6c9"),
                            Age = "10",
                            Email = "Email41@gmail.com",
                            FirstName = "FirstName41",
                            IsDeleted = false,
                            LastName = "LastName41",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("dd8c0cac-cbaa-4004-b761-8e223d5f2795"),
                            Age = "10",
                            Email = "Email42@gmail.com",
                            FirstName = "FirstName42",
                            IsDeleted = false,
                            LastName = "LastName42",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("7a0a1a23-fb0a-4cba-9f8d-e93cbbeb234f"),
                            Age = "10",
                            Email = "Email43@gmail.com",
                            FirstName = "FirstName43",
                            IsDeleted = false,
                            LastName = "LastName43",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("130d1b0b-1b06-4fff-a8c8-96386176b908"),
                            Age = "10",
                            Email = "Email44@gmail.com",
                            FirstName = "FirstName44",
                            IsDeleted = false,
                            LastName = "LastName44",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("b2d19002-b1c7-4e8d-9718-a0b04340096c"),
                            Age = "10",
                            Email = "Email45@gmail.com",
                            FirstName = "FirstName45",
                            IsDeleted = false,
                            LastName = "LastName45",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("e7753cec-b730-40b2-ba7d-a099c2bf6c8b"),
                            Age = "10",
                            Email = "Email46@gmail.com",
                            FirstName = "FirstName46",
                            IsDeleted = false,
                            LastName = "LastName46",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("ec1449cc-b75f-4e63-b037-e6f9e155224a"),
                            Age = "10",
                            Email = "Email47@gmail.com",
                            FirstName = "FirstName47",
                            IsDeleted = false,
                            LastName = "LastName47",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("53508434-c4d2-4e56-a9b9-fd0564b3e453"),
                            Age = "10",
                            Email = "Email48@gmail.com",
                            FirstName = "FirstName48",
                            IsDeleted = false,
                            LastName = "LastName48",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("8bfbb3bc-bf0a-41c9-8040-fe5cee93d6bf"),
                            Age = "10",
                            Email = "Email49@gmail.com",
                            FirstName = "FirstName49",
                            IsDeleted = false,
                            LastName = "LastName49",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("073fbb0c-5afa-4f88-bb75-2f8b3bfeb311"),
                            Age = "10",
                            Email = "Email50@gmail.com",
                            FirstName = "FirstName50",
                            IsDeleted = false,
                            LastName = "LastName50",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("080acfd4-9961-4167-ad99-885698b36e40"),
                            Age = "10",
                            Email = "Email51@gmail.com",
                            FirstName = "FirstName51",
                            IsDeleted = false,
                            LastName = "LastName51",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("43325b97-6cc5-410f-8b41-85b9b07fdfb2"),
                            Age = "10",
                            Email = "Email52@gmail.com",
                            FirstName = "FirstName52",
                            IsDeleted = false,
                            LastName = "LastName52",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("43db97af-cd59-4353-a416-00e5da49f7d5"),
                            Age = "10",
                            Email = "Email53@gmail.com",
                            FirstName = "FirstName53",
                            IsDeleted = false,
                            LastName = "LastName53",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("eaf09a1d-63de-4924-92c4-ff1723831bbc"),
                            Age = "10",
                            Email = "Email54@gmail.com",
                            FirstName = "FirstName54",
                            IsDeleted = false,
                            LastName = "LastName54",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("6e909780-4d15-4340-ba33-f9eb187a9fb3"),
                            Age = "10",
                            Email = "Email55@gmail.com",
                            FirstName = "FirstName55",
                            IsDeleted = false,
                            LastName = "LastName55",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("028e45ba-9c73-4209-9b5a-8a267a699a92"),
                            Age = "10",
                            Email = "Email56@gmail.com",
                            FirstName = "FirstName56",
                            IsDeleted = false,
                            LastName = "LastName56",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("f414eed1-a2a8-48aa-bf88-4fffe76742d6"),
                            Age = "10",
                            Email = "Email57@gmail.com",
                            FirstName = "FirstName57",
                            IsDeleted = false,
                            LastName = "LastName57",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("acba4426-c036-4bc9-b188-ac114d7094fd"),
                            Age = "10",
                            Email = "Email58@gmail.com",
                            FirstName = "FirstName58",
                            IsDeleted = false,
                            LastName = "LastName58",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("684aa4a3-9039-48f3-bd15-abaa8b2c38ff"),
                            Age = "10",
                            Email = "Email59@gmail.com",
                            FirstName = "FirstName59",
                            IsDeleted = false,
                            LastName = "LastName59",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("a0f38c43-f808-40fa-96c2-e765fea61a08"),
                            Age = "10",
                            Email = "Email60@gmail.com",
                            FirstName = "FirstName60",
                            IsDeleted = false,
                            LastName = "LastName60",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("408b1580-a86b-474d-9b6a-3fc151d99351"),
                            Age = "10",
                            Email = "Email61@gmail.com",
                            FirstName = "FirstName61",
                            IsDeleted = false,
                            LastName = "LastName61",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("67a55c6b-0bdd-48ef-ba2e-76cac07585e9"),
                            Age = "10",
                            Email = "Email62@gmail.com",
                            FirstName = "FirstName62",
                            IsDeleted = false,
                            LastName = "LastName62",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("67dbbaaa-bbd2-4d5d-87ee-89b00190ea3f"),
                            Age = "10",
                            Email = "Email63@gmail.com",
                            FirstName = "FirstName63",
                            IsDeleted = false,
                            LastName = "LastName63",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("81990843-7bb2-4f94-9cf9-89ee72be7a53"),
                            Age = "10",
                            Email = "Email64@gmail.com",
                            FirstName = "FirstName64",
                            IsDeleted = false,
                            LastName = "LastName64",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("ab76dc5e-73c2-4626-8fc4-1d2847c5d793"),
                            Age = "10",
                            Email = "Email65@gmail.com",
                            FirstName = "FirstName65",
                            IsDeleted = false,
                            LastName = "LastName65",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("d3f0ca8a-c662-4842-a310-d71d11d5b25a"),
                            Age = "10",
                            Email = "Email66@gmail.com",
                            FirstName = "FirstName66",
                            IsDeleted = false,
                            LastName = "LastName66",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("cf79b003-bd3c-4dab-b4f6-5b5010e68334"),
                            Age = "10",
                            Email = "Email67@gmail.com",
                            FirstName = "FirstName67",
                            IsDeleted = false,
                            LastName = "LastName67",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("1a11594f-8a31-4ba8-b6bf-9a31a10628ad"),
                            Age = "10",
                            Email = "Email68@gmail.com",
                            FirstName = "FirstName68",
                            IsDeleted = false,
                            LastName = "LastName68",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("f1c203b8-ff75-409a-8676-89424233f8ac"),
                            Age = "10",
                            Email = "Email69@gmail.com",
                            FirstName = "FirstName69",
                            IsDeleted = false,
                            LastName = "LastName69",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("5618e671-221f-4118-8cd1-82ed9d009076"),
                            Age = "10",
                            Email = "Email70@gmail.com",
                            FirstName = "FirstName70",
                            IsDeleted = false,
                            LastName = "LastName70",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("11860f0e-25fb-464f-bed2-ba6048f772db"),
                            Age = "10",
                            Email = "Email71@gmail.com",
                            FirstName = "FirstName71",
                            IsDeleted = false,
                            LastName = "LastName71",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("1a1f2d04-f8c2-4139-b6e7-4954ddc9bc12"),
                            Age = "10",
                            Email = "Email72@gmail.com",
                            FirstName = "FirstName72",
                            IsDeleted = false,
                            LastName = "LastName72",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("afd496f8-bf08-4524-bd90-743b62219606"),
                            Age = "10",
                            Email = "Email73@gmail.com",
                            FirstName = "FirstName73",
                            IsDeleted = false,
                            LastName = "LastName73",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("33ec6a29-7a9b-4bab-ab1f-7ee8cca5ea6f"),
                            Age = "10",
                            Email = "Email74@gmail.com",
                            FirstName = "FirstName74",
                            IsDeleted = false,
                            LastName = "LastName74",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("1d356843-478d-4165-a2ba-d74b2dea5e11"),
                            Age = "10",
                            Email = "Email75@gmail.com",
                            FirstName = "FirstName75",
                            IsDeleted = false,
                            LastName = "LastName75",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("23a756ba-76c6-49c1-991b-e216ee0487e8"),
                            Age = "10",
                            Email = "Email76@gmail.com",
                            FirstName = "FirstName76",
                            IsDeleted = false,
                            LastName = "LastName76",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("3e331450-7f98-4d34-bdac-fe7b05b6dc13"),
                            Age = "10",
                            Email = "Email77@gmail.com",
                            FirstName = "FirstName77",
                            IsDeleted = false,
                            LastName = "LastName77",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("bba156f4-1fc1-4830-b92a-846f2af6fa0d"),
                            Age = "10",
                            Email = "Email78@gmail.com",
                            FirstName = "FirstName78",
                            IsDeleted = false,
                            LastName = "LastName78",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("be33735f-94dc-4050-8e0b-e9d78354b8d2"),
                            Age = "10",
                            Email = "Email79@gmail.com",
                            FirstName = "FirstName79",
                            IsDeleted = false,
                            LastName = "LastName79",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("f6987580-4707-4ce4-8fe9-9bb4fada8f2b"),
                            Age = "10",
                            Email = "Email80@gmail.com",
                            FirstName = "FirstName80",
                            IsDeleted = false,
                            LastName = "LastName80",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("553aff4e-c7cc-4912-9124-c0eebfd3ba35"),
                            Age = "10",
                            Email = "Email81@gmail.com",
                            FirstName = "FirstName81",
                            IsDeleted = false,
                            LastName = "LastName81",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("516cd00d-c972-4baa-81dc-341a0f0b68a6"),
                            Age = "10",
                            Email = "Email82@gmail.com",
                            FirstName = "FirstName82",
                            IsDeleted = false,
                            LastName = "LastName82",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("29b13c14-7d5c-400c-9695-06abec38c3ea"),
                            Age = "10",
                            Email = "Email83@gmail.com",
                            FirstName = "FirstName83",
                            IsDeleted = false,
                            LastName = "LastName83",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("346198f5-1197-42f7-b59a-d254fc8413c1"),
                            Age = "10",
                            Email = "Email84@gmail.com",
                            FirstName = "FirstName84",
                            IsDeleted = false,
                            LastName = "LastName84",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("783dacaa-a034-46bc-a9d1-84a323d03073"),
                            Age = "10",
                            Email = "Email85@gmail.com",
                            FirstName = "FirstName85",
                            IsDeleted = false,
                            LastName = "LastName85",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("a9f7b272-5047-465e-abe4-4a4828c1a255"),
                            Age = "10",
                            Email = "Email86@gmail.com",
                            FirstName = "FirstName86",
                            IsDeleted = false,
                            LastName = "LastName86",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("b16e08ab-75cc-45ff-b3ef-f1f93db2765e"),
                            Age = "10",
                            Email = "Email87@gmail.com",
                            FirstName = "FirstName87",
                            IsDeleted = false,
                            LastName = "LastName87",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("253b4566-24a3-4ca4-a7c2-27435701fec6"),
                            Age = "10",
                            Email = "Email88@gmail.com",
                            FirstName = "FirstName88",
                            IsDeleted = false,
                            LastName = "LastName88",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("d5850422-fb62-48df-b2d2-1977ffea6a17"),
                            Age = "10",
                            Email = "Email89@gmail.com",
                            FirstName = "FirstName89",
                            IsDeleted = false,
                            LastName = "LastName89",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("fd540831-2104-4c7c-af87-1aea85e52351"),
                            Age = "10",
                            Email = "Email90@gmail.com",
                            FirstName = "FirstName90",
                            IsDeleted = false,
                            LastName = "LastName90",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("087594b1-e612-4b59-a160-0e60b8d65128"),
                            Age = "10",
                            Email = "Email91@gmail.com",
                            FirstName = "FirstName91",
                            IsDeleted = false,
                            LastName = "LastName91",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("4cc4bd2a-892e-4768-b0b7-35a0a0849e5d"),
                            Age = "10",
                            Email = "Email92@gmail.com",
                            FirstName = "FirstName92",
                            IsDeleted = false,
                            LastName = "LastName92",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("b3310277-fe2e-4084-b914-bca6fa84e786"),
                            Age = "10",
                            Email = "Email93@gmail.com",
                            FirstName = "FirstName93",
                            IsDeleted = false,
                            LastName = "LastName93",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("3905cc17-7ff8-4b4f-962c-b91742b3c095"),
                            Age = "10",
                            Email = "Email94@gmail.com",
                            FirstName = "FirstName94",
                            IsDeleted = false,
                            LastName = "LastName94",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("806277d5-6ab4-4d33-86f2-94c54a3cac4b"),
                            Age = "10",
                            Email = "Email95@gmail.com",
                            FirstName = "FirstName95",
                            IsDeleted = false,
                            LastName = "LastName95",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("af2dacb0-9860-4a50-a19f-d90eaf46c406"),
                            Age = "10",
                            Email = "Email96@gmail.com",
                            FirstName = "FirstName96",
                            IsDeleted = false,
                            LastName = "LastName96",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("a62970a6-58c7-4b0a-bba0-a8a55b013e26"),
                            Age = "10",
                            Email = "Email97@gmail.com",
                            FirstName = "FirstName97",
                            IsDeleted = false,
                            LastName = "LastName97",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("e35b72b2-d5a6-49e5-b24b-bd33344b3371"),
                            Age = "10",
                            Email = "Email98@gmail.com",
                            FirstName = "FirstName98",
                            IsDeleted = false,
                            LastName = "LastName98",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("0dcb00b5-be6c-4021-bbfd-4d9b8c69d092"),
                            Age = "10",
                            Email = "Email99@gmail.com",
                            FirstName = "FirstName99",
                            IsDeleted = false,
                            LastName = "LastName99",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student",
                            SendDate = new DateOnly(1, 1, 1)
                        });
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.ApplyRequest", b =>
                {
                    b.HasOne("DOTNET_hocmienphi.repository.entity.User", "User")
                        .WithMany("ApplyRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.ApplyRequestCategory", b =>
                {
                    b.HasOne("DOTNET_hocmienphi.repository.entity.ApplyRequest", "ApplyRequest")
                        .WithMany("ApplyRequestCategories")
                        .HasForeignKey("ApplyRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DOTNET_hocmienphi.repository.entity.Category", "Category")
                        .WithMany("ApplyRequestCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplyRequest");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Booking", b =>
                {
                    b.HasOne("DOTNET_hocmienphi.repository.entity.Mentor", "Mentor")
                        .WithMany("Bookings")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DOTNET_hocmienphi.repository.entity.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mentor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Category", b =>
                {
                    b.HasOne("DOTNET_hocmienphi.repository.entity.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Mentor", b =>
                {
                    b.HasOne("DOTNET_hocmienphi.repository.entity.User", "User")
                        .WithOne("Mentor")
                        .HasForeignKey("DOTNET_hocmienphi.repository.entity.Mentor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.MentorCategory", b =>
                {
                    b.HasOne("DOTNET_hocmienphi.repository.entity.Category", "Category")
                        .WithMany("MentorCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DOTNET_hocmienphi.repository.entity.Mentor", "Mentor")
                        .WithMany("MentorCategories")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.MentorFreetime", b =>
                {
                    b.HasOne("DOTNET_hocmienphi.repository.entity.Mentor", "Mentor")
                        .WithMany("MentorFreetimes")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.ApplyRequest", b =>
                {
                    b.Navigation("ApplyRequestCategories");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Category", b =>
                {
                    b.Navigation("ApplyRequestCategories");

                    b.Navigation("Children");

                    b.Navigation("MentorCategories");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Mentor", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("MentorCategories");

                    b.Navigation("MentorFreetimes");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.User", b =>
                {
                    b.Navigation("ApplyRequests");

                    b.Navigation("Bookings");

                    b.Navigation("Mentor");
                });
#pragma warning restore 612, 618
        }
    }
}
