// <auto-generated />
using System;
using DOTNET_hocmienphi.repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DOTNET_hocmienphi.repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260619100952_ApplyRequestCategoryTable")]
    partial class ApplyRequestCategoryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.ApplyRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CvLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("RejectReason")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ApplyRequests");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.ApplyRequestCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplyRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ApplyRequestId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ApplyRequestCategories");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MentorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StarTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MentorId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Mentor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentPosition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Mentors");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.MentorCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MentorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("MentorId");

                    b.ToTable("MentorCategories");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.MentorFreetime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DateOfWeek")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MentorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MentorId");

                    b.ToTable("MentorFreetimes");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("edb5297f-61ae-41f0-9a36-9350614b759f"),
                            Age = "10",
                            Email = "Email0@gmail.com",
                            FirstName = "FirstName0",
                            IsDeleted = false,
                            LastName = "LastName0",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("4bb53bde-7c6b-45c4-a072-4a3d4816472c"),
                            Age = "10",
                            Email = "Email1@gmail.com",
                            FirstName = "FirstName1",
                            IsDeleted = false,
                            LastName = "LastName1",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("8f59f6b7-d846-4b17-84c0-a9c9da6d5a36"),
                            Age = "10",
                            Email = "Email2@gmail.com",
                            FirstName = "FirstName2",
                            IsDeleted = false,
                            LastName = "LastName2",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("db14a0f4-1987-4a26-b470-d88e66ece3ab"),
                            Age = "10",
                            Email = "Email3@gmail.com",
                            FirstName = "FirstName3",
                            IsDeleted = false,
                            LastName = "LastName3",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("7b32e7ef-04c7-4ca2-a128-e1be30a7ab9a"),
                            Age = "10",
                            Email = "Email4@gmail.com",
                            FirstName = "FirstName4",
                            IsDeleted = false,
                            LastName = "LastName4",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("b13a537d-29e6-4d6b-ba4b-0c7648b2936c"),
                            Age = "10",
                            Email = "Email5@gmail.com",
                            FirstName = "FirstName5",
                            IsDeleted = false,
                            LastName = "LastName5",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("9eab64d8-ab11-4fa0-b101-43abaa3445e4"),
                            Age = "10",
                            Email = "Email6@gmail.com",
                            FirstName = "FirstName6",
                            IsDeleted = false,
                            LastName = "LastName6",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("8f4d8940-a05d-4c11-8673-56b4ab6d3a73"),
                            Age = "10",
                            Email = "Email7@gmail.com",
                            FirstName = "FirstName7",
                            IsDeleted = false,
                            LastName = "LastName7",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("86507b3d-ddbc-49a7-87bd-47b7502bdb56"),
                            Age = "10",
                            Email = "Email8@gmail.com",
                            FirstName = "FirstName8",
                            IsDeleted = false,
                            LastName = "LastName8",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("ec42b80d-7dc5-4edb-8e9c-366733feb245"),
                            Age = "10",
                            Email = "Email9@gmail.com",
                            FirstName = "FirstName9",
                            IsDeleted = false,
                            LastName = "LastName9",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("a25a291c-6868-4868-a726-2e7595030053"),
                            Age = "10",
                            Email = "Email10@gmail.com",
                            FirstName = "FirstName10",
                            IsDeleted = false,
                            LastName = "LastName10",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("1fe2fbb1-b547-422a-9cae-7ce4c99ab301"),
                            Age = "10",
                            Email = "Email11@gmail.com",
                            FirstName = "FirstName11",
                            IsDeleted = false,
                            LastName = "LastName11",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("a49e7606-2379-47e3-be13-48b60053578a"),
                            Age = "10",
                            Email = "Email12@gmail.com",
                            FirstName = "FirstName12",
                            IsDeleted = false,
                            LastName = "LastName12",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("3fabf8ff-b653-4204-8e10-de0c013be95d"),
                            Age = "10",
                            Email = "Email13@gmail.com",
                            FirstName = "FirstName13",
                            IsDeleted = false,
                            LastName = "LastName13",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("28b0c24e-e97d-4487-9285-1c056a8c44af"),
                            Age = "10",
                            Email = "Email14@gmail.com",
                            FirstName = "FirstName14",
                            IsDeleted = false,
                            LastName = "LastName14",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("f364e560-1dfa-4d64-99c0-bcf93ae4acab"),
                            Age = "10",
                            Email = "Email15@gmail.com",
                            FirstName = "FirstName15",
                            IsDeleted = false,
                            LastName = "LastName15",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("982b560d-387e-45a0-a40c-c0fe3178c357"),
                            Age = "10",
                            Email = "Email16@gmail.com",
                            FirstName = "FirstName16",
                            IsDeleted = false,
                            LastName = "LastName16",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("7510be2e-c751-485c-b64c-4ad8496a3f8c"),
                            Age = "10",
                            Email = "Email17@gmail.com",
                            FirstName = "FirstName17",
                            IsDeleted = false,
                            LastName = "LastName17",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("fe070dba-2fa2-4d9a-97f7-d9953789814a"),
                            Age = "10",
                            Email = "Email18@gmail.com",
                            FirstName = "FirstName18",
                            IsDeleted = false,
                            LastName = "LastName18",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("d82dec76-1164-4773-92ca-143d65dde3e9"),
                            Age = "10",
                            Email = "Email19@gmail.com",
                            FirstName = "FirstName19",
                            IsDeleted = false,
                            LastName = "LastName19",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("c2b9abec-343b-447f-853d-c22960d6095e"),
                            Age = "10",
                            Email = "Email20@gmail.com",
                            FirstName = "FirstName20",
                            IsDeleted = false,
                            LastName = "LastName20",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("f6047979-de63-4ef9-bfc6-ffe998546539"),
                            Age = "10",
                            Email = "Email21@gmail.com",
                            FirstName = "FirstName21",
                            IsDeleted = false,
                            LastName = "LastName21",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("115eb520-d368-4b71-8e03-917a5ae23d7e"),
                            Age = "10",
                            Email = "Email22@gmail.com",
                            FirstName = "FirstName22",
                            IsDeleted = false,
                            LastName = "LastName22",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("9c14ba75-e53e-4df8-85f2-d54ab0400100"),
                            Age = "10",
                            Email = "Email23@gmail.com",
                            FirstName = "FirstName23",
                            IsDeleted = false,
                            LastName = "LastName23",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("f1d06f83-4344-4758-83a5-ea6f010520ce"),
                            Age = "10",
                            Email = "Email24@gmail.com",
                            FirstName = "FirstName24",
                            IsDeleted = false,
                            LastName = "LastName24",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("d5d36b57-af2f-4b01-996f-851e4512bc78"),
                            Age = "10",
                            Email = "Email25@gmail.com",
                            FirstName = "FirstName25",
                            IsDeleted = false,
                            LastName = "LastName25",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("1e95f099-4e08-4d80-8e9f-409c106e5e0c"),
                            Age = "10",
                            Email = "Email26@gmail.com",
                            FirstName = "FirstName26",
                            IsDeleted = false,
                            LastName = "LastName26",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("522b556a-8c9e-4435-adb4-26138c097da6"),
                            Age = "10",
                            Email = "Email27@gmail.com",
                            FirstName = "FirstName27",
                            IsDeleted = false,
                            LastName = "LastName27",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("2dfe3836-86df-4e0b-a6be-1dfc98c1e245"),
                            Age = "10",
                            Email = "Email28@gmail.com",
                            FirstName = "FirstName28",
                            IsDeleted = false,
                            LastName = "LastName28",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("48d0f8c9-ae04-4683-963e-5207183519bb"),
                            Age = "10",
                            Email = "Email29@gmail.com",
                            FirstName = "FirstName29",
                            IsDeleted = false,
                            LastName = "LastName29",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("5d35b81e-e1e2-4a87-ac28-54af371c5fbd"),
                            Age = "10",
                            Email = "Email30@gmail.com",
                            FirstName = "FirstName30",
                            IsDeleted = false,
                            LastName = "LastName30",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("1d7c5dd5-106b-4f83-a798-9c9d70c89ee5"),
                            Age = "10",
                            Email = "Email31@gmail.com",
                            FirstName = "FirstName31",
                            IsDeleted = false,
                            LastName = "LastName31",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("6f86cf32-0b1a-44c4-92de-5aeffdc64695"),
                            Age = "10",
                            Email = "Email32@gmail.com",
                            FirstName = "FirstName32",
                            IsDeleted = false,
                            LastName = "LastName32",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("45008283-b464-47e3-86bb-b696a4baaf4e"),
                            Age = "10",
                            Email = "Email33@gmail.com",
                            FirstName = "FirstName33",
                            IsDeleted = false,
                            LastName = "LastName33",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("b3013911-08ea-4292-af26-b21980d094e2"),
                            Age = "10",
                            Email = "Email34@gmail.com",
                            FirstName = "FirstName34",
                            IsDeleted = false,
                            LastName = "LastName34",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("5ee183ac-97bd-473f-9e24-afb2dacb4ffe"),
                            Age = "10",
                            Email = "Email35@gmail.com",
                            FirstName = "FirstName35",
                            IsDeleted = false,
                            LastName = "LastName35",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("a833be8a-1a99-4129-a84d-716786cd463d"),
                            Age = "10",
                            Email = "Email36@gmail.com",
                            FirstName = "FirstName36",
                            IsDeleted = false,
                            LastName = "LastName36",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("7748be6f-2b36-4df8-be91-2391cbc1d98c"),
                            Age = "10",
                            Email = "Email37@gmail.com",
                            FirstName = "FirstName37",
                            IsDeleted = false,
                            LastName = "LastName37",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("c3390945-ec83-468f-a4a2-32e3dd82ee0e"),
                            Age = "10",
                            Email = "Email38@gmail.com",
                            FirstName = "FirstName38",
                            IsDeleted = false,
                            LastName = "LastName38",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("d502bc46-b8e7-46c6-b5ba-944cdd987aa7"),
                            Age = "10",
                            Email = "Email39@gmail.com",
                            FirstName = "FirstName39",
                            IsDeleted = false,
                            LastName = "LastName39",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("74062231-04e7-4628-973c-230fdf16819b"),
                            Age = "10",
                            Email = "Email40@gmail.com",
                            FirstName = "FirstName40",
                            IsDeleted = false,
                            LastName = "LastName40",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("e169e1f4-2c42-47da-a5c0-b60cb02dc085"),
                            Age = "10",
                            Email = "Email41@gmail.com",
                            FirstName = "FirstName41",
                            IsDeleted = false,
                            LastName = "LastName41",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("14ca906c-64d8-4342-a372-b0c640e6303f"),
                            Age = "10",
                            Email = "Email42@gmail.com",
                            FirstName = "FirstName42",
                            IsDeleted = false,
                            LastName = "LastName42",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("be406f0a-f52d-4206-9c75-13a154bbea33"),
                            Age = "10",
                            Email = "Email43@gmail.com",
                            FirstName = "FirstName43",
                            IsDeleted = false,
                            LastName = "LastName43",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("aacd5d84-3100-402b-8e93-8cfd6f95bd28"),
                            Age = "10",
                            Email = "Email44@gmail.com",
                            FirstName = "FirstName44",
                            IsDeleted = false,
                            LastName = "LastName44",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("a02508b8-ef4a-430a-a528-13acadb531fa"),
                            Age = "10",
                            Email = "Email45@gmail.com",
                            FirstName = "FirstName45",
                            IsDeleted = false,
                            LastName = "LastName45",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("c3ae786a-e593-430b-9264-a7b71c1c87e4"),
                            Age = "10",
                            Email = "Email46@gmail.com",
                            FirstName = "FirstName46",
                            IsDeleted = false,
                            LastName = "LastName46",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("b8a10942-5a49-4932-94b4-605d8de1bee9"),
                            Age = "10",
                            Email = "Email47@gmail.com",
                            FirstName = "FirstName47",
                            IsDeleted = false,
                            LastName = "LastName47",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("bb639511-44fd-40d0-94a8-7f60a187cc93"),
                            Age = "10",
                            Email = "Email48@gmail.com",
                            FirstName = "FirstName48",
                            IsDeleted = false,
                            LastName = "LastName48",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("22114a16-85f4-4ddf-9d29-1ae90cef46c8"),
                            Age = "10",
                            Email = "Email49@gmail.com",
                            FirstName = "FirstName49",
                            IsDeleted = false,
                            LastName = "LastName49",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("e3b1087d-6e3a-49d0-adcd-67459e2f84ed"),
                            Age = "10",
                            Email = "Email50@gmail.com",
                            FirstName = "FirstName50",
                            IsDeleted = false,
                            LastName = "LastName50",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("e87a8bdd-299f-4619-b917-67b76eee3c99"),
                            Age = "10",
                            Email = "Email51@gmail.com",
                            FirstName = "FirstName51",
                            IsDeleted = false,
                            LastName = "LastName51",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("f12c912f-1dd3-48ab-be75-ba7956a2e515"),
                            Age = "10",
                            Email = "Email52@gmail.com",
                            FirstName = "FirstName52",
                            IsDeleted = false,
                            LastName = "LastName52",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("355e0108-3166-4f91-9a96-eaffa08fb6ca"),
                            Age = "10",
                            Email = "Email53@gmail.com",
                            FirstName = "FirstName53",
                            IsDeleted = false,
                            LastName = "LastName53",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("307e22b8-c7cb-4629-a7dc-54f1bad5a115"),
                            Age = "10",
                            Email = "Email54@gmail.com",
                            FirstName = "FirstName54",
                            IsDeleted = false,
                            LastName = "LastName54",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("dd640eb8-74f1-4ae1-897b-6785d1f3f900"),
                            Age = "10",
                            Email = "Email55@gmail.com",
                            FirstName = "FirstName55",
                            IsDeleted = false,
                            LastName = "LastName55",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("556e15b3-596a-42bc-ac40-c15bed1a3f7f"),
                            Age = "10",
                            Email = "Email56@gmail.com",
                            FirstName = "FirstName56",
                            IsDeleted = false,
                            LastName = "LastName56",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("00c3da93-57d5-4e0b-b774-b4bfb1160f2a"),
                            Age = "10",
                            Email = "Email57@gmail.com",
                            FirstName = "FirstName57",
                            IsDeleted = false,
                            LastName = "LastName57",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("9f78ab67-f71a-42d4-aef4-da2526bf30f3"),
                            Age = "10",
                            Email = "Email58@gmail.com",
                            FirstName = "FirstName58",
                            IsDeleted = false,
                            LastName = "LastName58",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("bc9fd52c-cdf8-458f-83a8-de7a4f33fa6f"),
                            Age = "10",
                            Email = "Email59@gmail.com",
                            FirstName = "FirstName59",
                            IsDeleted = false,
                            LastName = "LastName59",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("a0c52f2f-5739-47e6-9130-b3d6c94ff54a"),
                            Age = "10",
                            Email = "Email60@gmail.com",
                            FirstName = "FirstName60",
                            IsDeleted = false,
                            LastName = "LastName60",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("d056d758-cbfc-4041-a5de-4e95a39f36be"),
                            Age = "10",
                            Email = "Email61@gmail.com",
                            FirstName = "FirstName61",
                            IsDeleted = false,
                            LastName = "LastName61",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("1cf3d78b-ac90-4cdc-ad6c-8a6f98d763d0"),
                            Age = "10",
                            Email = "Email62@gmail.com",
                            FirstName = "FirstName62",
                            IsDeleted = false,
                            LastName = "LastName62",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("af5d5a00-c8df-4552-92eb-2208161b3668"),
                            Age = "10",
                            Email = "Email63@gmail.com",
                            FirstName = "FirstName63",
                            IsDeleted = false,
                            LastName = "LastName63",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("c6a92001-dff7-4ac7-af26-0b1f4525d10e"),
                            Age = "10",
                            Email = "Email64@gmail.com",
                            FirstName = "FirstName64",
                            IsDeleted = false,
                            LastName = "LastName64",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("6426d2c2-04c4-42ef-ad0f-b9583e0a6246"),
                            Age = "10",
                            Email = "Email65@gmail.com",
                            FirstName = "FirstName65",
                            IsDeleted = false,
                            LastName = "LastName65",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("9acab135-437e-47c8-8a2b-302eeb2f2111"),
                            Age = "10",
                            Email = "Email66@gmail.com",
                            FirstName = "FirstName66",
                            IsDeleted = false,
                            LastName = "LastName66",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("5bf2b4d2-d692-4839-ab77-1659f7b7179c"),
                            Age = "10",
                            Email = "Email67@gmail.com",
                            FirstName = "FirstName67",
                            IsDeleted = false,
                            LastName = "LastName67",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("762deec3-5323-488f-be42-57841bd186b3"),
                            Age = "10",
                            Email = "Email68@gmail.com",
                            FirstName = "FirstName68",
                            IsDeleted = false,
                            LastName = "LastName68",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("0136a24b-43ff-4f33-82e7-5ce70a819cbd"),
                            Age = "10",
                            Email = "Email69@gmail.com",
                            FirstName = "FirstName69",
                            IsDeleted = false,
                            LastName = "LastName69",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("100464ec-ede3-42b0-8a1c-24bd4084fc38"),
                            Age = "10",
                            Email = "Email70@gmail.com",
                            FirstName = "FirstName70",
                            IsDeleted = false,
                            LastName = "LastName70",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("0b0699cc-b726-41bf-afef-f55554fcc6ad"),
                            Age = "10",
                            Email = "Email71@gmail.com",
                            FirstName = "FirstName71",
                            IsDeleted = false,
                            LastName = "LastName71",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("967e28ad-b990-4441-ab17-e6b306f62e52"),
                            Age = "10",
                            Email = "Email72@gmail.com",
                            FirstName = "FirstName72",
                            IsDeleted = false,
                            LastName = "LastName72",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("819dcad3-d5d7-4a6d-b97a-049e59b190c1"),
                            Age = "10",
                            Email = "Email73@gmail.com",
                            FirstName = "FirstName73",
                            IsDeleted = false,
                            LastName = "LastName73",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("22e71c2c-2730-46f7-b4c6-eca061f554fc"),
                            Age = "10",
                            Email = "Email74@gmail.com",
                            FirstName = "FirstName74",
                            IsDeleted = false,
                            LastName = "LastName74",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("5bdc2356-1bb6-48a3-8a74-5775c532cfd9"),
                            Age = "10",
                            Email = "Email75@gmail.com",
                            FirstName = "FirstName75",
                            IsDeleted = false,
                            LastName = "LastName75",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("1cd237a7-2753-4055-beff-edbeb2131ca9"),
                            Age = "10",
                            Email = "Email76@gmail.com",
                            FirstName = "FirstName76",
                            IsDeleted = false,
                            LastName = "LastName76",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("12810f96-a4b9-469c-8439-e8d8bb5b81c3"),
                            Age = "10",
                            Email = "Email77@gmail.com",
                            FirstName = "FirstName77",
                            IsDeleted = false,
                            LastName = "LastName77",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("2573022b-2526-4986-98fd-31fa0e018a2c"),
                            Age = "10",
                            Email = "Email78@gmail.com",
                            FirstName = "FirstName78",
                            IsDeleted = false,
                            LastName = "LastName78",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("b2cec74a-6395-48ee-8107-48494327367e"),
                            Age = "10",
                            Email = "Email79@gmail.com",
                            FirstName = "FirstName79",
                            IsDeleted = false,
                            LastName = "LastName79",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("fdd5f1d6-d6b2-4232-9ade-8a7eaffb9d11"),
                            Age = "10",
                            Email = "Email80@gmail.com",
                            FirstName = "FirstName80",
                            IsDeleted = false,
                            LastName = "LastName80",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("f1b81755-ec14-4d02-b8c9-e3d5fa283c31"),
                            Age = "10",
                            Email = "Email81@gmail.com",
                            FirstName = "FirstName81",
                            IsDeleted = false,
                            LastName = "LastName81",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("a80b76e0-b601-412a-9563-26f9ba4bb9ac"),
                            Age = "10",
                            Email = "Email82@gmail.com",
                            FirstName = "FirstName82",
                            IsDeleted = false,
                            LastName = "LastName82",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("934bf105-9ff1-4944-bec8-9823e59938b8"),
                            Age = "10",
                            Email = "Email83@gmail.com",
                            FirstName = "FirstName83",
                            IsDeleted = false,
                            LastName = "LastName83",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("181162ce-31b9-4d89-ac96-b6c34f50205c"),
                            Age = "10",
                            Email = "Email84@gmail.com",
                            FirstName = "FirstName84",
                            IsDeleted = false,
                            LastName = "LastName84",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("af459baa-37bf-4bac-a04d-26419307aac7"),
                            Age = "10",
                            Email = "Email85@gmail.com",
                            FirstName = "FirstName85",
                            IsDeleted = false,
                            LastName = "LastName85",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("4f916359-f8b2-417c-a249-e34ea6f8ae22"),
                            Age = "10",
                            Email = "Email86@gmail.com",
                            FirstName = "FirstName86",
                            IsDeleted = false,
                            LastName = "LastName86",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("a3953c93-46d5-486e-bb3f-c2677a0fb7be"),
                            Age = "10",
                            Email = "Email87@gmail.com",
                            FirstName = "FirstName87",
                            IsDeleted = false,
                            LastName = "LastName87",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("96fac293-d0c9-4a78-ac24-4bafc408cc03"),
                            Age = "10",
                            Email = "Email88@gmail.com",
                            FirstName = "FirstName88",
                            IsDeleted = false,
                            LastName = "LastName88",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("c1bad89f-b587-49c9-a8b0-01f05dccad94"),
                            Age = "10",
                            Email = "Email89@gmail.com",
                            FirstName = "FirstName89",
                            IsDeleted = false,
                            LastName = "LastName89",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("1c9abaa1-b81f-48f4-894f-233201dd84a1"),
                            Age = "10",
                            Email = "Email90@gmail.com",
                            FirstName = "FirstName90",
                            IsDeleted = false,
                            LastName = "LastName90",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("57bd49ce-a36d-4d87-937a-852aa246ec36"),
                            Age = "10",
                            Email = "Email91@gmail.com",
                            FirstName = "FirstName91",
                            IsDeleted = false,
                            LastName = "LastName91",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("68c7995a-dd78-4691-91a6-c99a19fa0336"),
                            Age = "10",
                            Email = "Email92@gmail.com",
                            FirstName = "FirstName92",
                            IsDeleted = false,
                            LastName = "LastName92",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("7667d5a6-1bc6-448c-80b5-218d7ba6ed48"),
                            Age = "10",
                            Email = "Email93@gmail.com",
                            FirstName = "FirstName93",
                            IsDeleted = false,
                            LastName = "LastName93",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("71b398d7-a5e2-4ade-80b0-6b8e6e67308b"),
                            Age = "10",
                            Email = "Email94@gmail.com",
                            FirstName = "FirstName94",
                            IsDeleted = false,
                            LastName = "LastName94",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("4bb5bcab-ab74-41e6-9349-98a2497d6284"),
                            Age = "10",
                            Email = "Email95@gmail.com",
                            FirstName = "FirstName95",
                            IsDeleted = false,
                            LastName = "LastName95",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("20dfc7b6-1578-4d3c-b6b3-10e3685230ab"),
                            Age = "10",
                            Email = "Email96@gmail.com",
                            FirstName = "FirstName96",
                            IsDeleted = false,
                            LastName = "LastName96",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("e9d1742d-997e-48b0-8441-1a4fefe10b3e"),
                            Age = "10",
                            Email = "Email97@gmail.com",
                            FirstName = "FirstName97",
                            IsDeleted = false,
                            LastName = "LastName97",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("b85c2145-2cee-4ddc-b84b-4093e476f8af"),
                            Age = "10",
                            Email = "Email98@gmail.com",
                            FirstName = "FirstName98",
                            IsDeleted = false,
                            LastName = "LastName98",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("3f4973ae-fc7c-40a9-aaf7-9554862186bf"),
                            Age = "10",
                            Email = "Email99@gmail.com",
                            FirstName = "FirstName99",
                            IsDeleted = false,
                            LastName = "LastName99",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        });
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.ApplyRequest", b =>
                {
                    b.HasOne("DOTNET_hocmienphi.repository.entity.User", "User")
                        .WithMany("ApplyRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.ApplyRequestCategory", b =>
                {
                    b.HasOne("DOTNET_hocmienphi.repository.entity.ApplyRequest", "ApplyRequest")
                        .WithMany("ApplyRequestCategories")
                        .HasForeignKey("ApplyRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DOTNET_hocmienphi.repository.entity.Category", "Category")
                        .WithMany("ApplyRequestCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplyRequest");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Booking", b =>
                {
                    b.HasOne("DOTNET_hocmienphi.repository.entity.Mentor", "Mentor")
                        .WithMany("Bookings")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DOTNET_hocmienphi.repository.entity.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mentor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Category", b =>
                {
                    b.HasOne("DOTNET_hocmienphi.repository.entity.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Mentor", b =>
                {
                    b.HasOne("DOTNET_hocmienphi.repository.entity.User", "User")
                        .WithOne("Mentor")
                        .HasForeignKey("DOTNET_hocmienphi.repository.entity.Mentor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.MentorCategory", b =>
                {
                    b.HasOne("DOTNET_hocmienphi.repository.entity.Category", "Category")
                        .WithMany("MentorCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DOTNET_hocmienphi.repository.entity.Mentor", "Mentor")
                        .WithMany("MentorCategories")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.MentorFreetime", b =>
                {
                    b.HasOne("DOTNET_hocmienphi.repository.entity.Mentor", "Mentor")
                        .WithMany("MentorFreetimes")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.ApplyRequest", b =>
                {
                    b.Navigation("ApplyRequestCategories");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Category", b =>
                {
                    b.Navigation("ApplyRequestCategories");

                    b.Navigation("Children");

                    b.Navigation("MentorCategories");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Mentor", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("MentorCategories");

                    b.Navigation("MentorFreetimes");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.User", b =>
                {
                    b.Navigation("ApplyRequests");

                    b.Navigation("Bookings");

                    b.Navigation("Mentor");
                });
#pragma warning restore 612, 618
        }
    }
}
