// <auto-generated />
using System;
using DOTNET_hocmienphi.repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DOTNET_hocmienphi.repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260619091357_ApplyRequestTable")]
    partial class ApplyRequestTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.ApplyRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CvLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("RejectReason")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ApplyRequest");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Meeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Mentor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentPosition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Mentors");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.MentorCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MentorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("MentorId");

                    b.ToTable("MentorCategories");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f59dfae-f135-42d1-838e-305dcce6d34c"),
                            Age = "10",
                            Email = "Email0@gmail.com",
                            FirstName = "FirstName0",
                            IsDeleted = false,
                            LastName = "LastName0",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("33d87290-4039-48e2-a438-d83c5dc03474"),
                            Age = "10",
                            Email = "Email1@gmail.com",
                            FirstName = "FirstName1",
                            IsDeleted = false,
                            LastName = "LastName1",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("412b3e12-d158-4237-bc65-840560a0e7b9"),
                            Age = "10",
                            Email = "Email2@gmail.com",
                            FirstName = "FirstName2",
                            IsDeleted = false,
                            LastName = "LastName2",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("3ecc20d5-3efc-40d1-b867-c482519baf52"),
                            Age = "10",
                            Email = "Email3@gmail.com",
                            FirstName = "FirstName3",
                            IsDeleted = false,
                            LastName = "LastName3",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("696b0b5d-78a2-4e4f-a18f-94d63015f154"),
                            Age = "10",
                            Email = "Email4@gmail.com",
                            FirstName = "FirstName4",
                            IsDeleted = false,
                            LastName = "LastName4",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("5f1b5b51-4f80-4685-925f-f81bb5c85e09"),
                            Age = "10",
                            Email = "Email5@gmail.com",
                            FirstName = "FirstName5",
                            IsDeleted = false,
                            LastName = "LastName5",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("d3cf8311-7b8b-4e8e-ac93-7b780906e9eb"),
                            Age = "10",
                            Email = "Email6@gmail.com",
                            FirstName = "FirstName6",
                            IsDeleted = false,
                            LastName = "LastName6",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("8ad54848-5ebd-4294-8b99-989a7fecfaec"),
                            Age = "10",
                            Email = "Email7@gmail.com",
                            FirstName = "FirstName7",
                            IsDeleted = false,
                            LastName = "LastName7",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("dea12766-a202-416f-acf8-0f32897dbbe9"),
                            Age = "10",
                            Email = "Email8@gmail.com",
                            FirstName = "FirstName8",
                            IsDeleted = false,
                            LastName = "LastName8",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("d220888e-49b1-47b2-bd23-00eaba7a86e6"),
                            Age = "10",
                            Email = "Email9@gmail.com",
                            FirstName = "FirstName9",
                            IsDeleted = false,
                            LastName = "LastName9",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("c15c3aa0-7747-41c7-b64b-0d32e3cde23c"),
                            Age = "10",
                            Email = "Email10@gmail.com",
                            FirstName = "FirstName10",
                            IsDeleted = false,
                            LastName = "LastName10",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("fe31ac8e-d595-4d18-879a-2e1401675bb2"),
                            Age = "10",
                            Email = "Email11@gmail.com",
                            FirstName = "FirstName11",
                            IsDeleted = false,
                            LastName = "LastName11",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("7d5cc50b-a97b-48c3-8793-ce80351923f5"),
                            Age = "10",
                            Email = "Email12@gmail.com",
                            FirstName = "FirstName12",
                            IsDeleted = false,
                            LastName = "LastName12",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("8ffacf42-afc3-497a-8076-820e30f745e3"),
                            Age = "10",
                            Email = "Email13@gmail.com",
                            FirstName = "FirstName13",
                            IsDeleted = false,
                            LastName = "LastName13",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("9f8eeb2c-4992-4f62-b32c-ee439d1458ca"),
                            Age = "10",
                            Email = "Email14@gmail.com",
                            FirstName = "FirstName14",
                            IsDeleted = false,
                            LastName = "LastName14",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("f171212d-447b-4ea5-96a9-7a2e4c8a4825"),
                            Age = "10",
                            Email = "Email15@gmail.com",
                            FirstName = "FirstName15",
                            IsDeleted = false,
                            LastName = "LastName15",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("6fb1ac4d-713c-41aa-a5fc-046734bcd009"),
                            Age = "10",
                            Email = "Email16@gmail.com",
                            FirstName = "FirstName16",
                            IsDeleted = false,
                            LastName = "LastName16",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("4ec04ff9-f901-4436-8fbe-2bae740ba5e9"),
                            Age = "10",
                            Email = "Email17@gmail.com",
                            FirstName = "FirstName17",
                            IsDeleted = false,
                            LastName = "LastName17",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("512ceb34-24d2-4487-a64b-634142b5d080"),
                            Age = "10",
                            Email = "Email18@gmail.com",
                            FirstName = "FirstName18",
                            IsDeleted = false,
                            LastName = "LastName18",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("2114501e-7db7-40bf-be71-3b17d3d58db7"),
                            Age = "10",
                            Email = "Email19@gmail.com",
                            FirstName = "FirstName19",
                            IsDeleted = false,
                            LastName = "LastName19",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("64dd0ee7-d47b-4fcc-bf69-6d61edd0a56b"),
                            Age = "10",
                            Email = "Email20@gmail.com",
                            FirstName = "FirstName20",
                            IsDeleted = false,
                            LastName = "LastName20",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("de72d37f-0778-4c53-80d0-2c47b96af874"),
                            Age = "10",
                            Email = "Email21@gmail.com",
                            FirstName = "FirstName21",
                            IsDeleted = false,
                            LastName = "LastName21",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("0501e018-c250-443e-9e69-faf64f623791"),
                            Age = "10",
                            Email = "Email22@gmail.com",
                            FirstName = "FirstName22",
                            IsDeleted = false,
                            LastName = "LastName22",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("f81b9553-28d5-4d66-9637-a87817059205"),
                            Age = "10",
                            Email = "Email23@gmail.com",
                            FirstName = "FirstName23",
                            IsDeleted = false,
                            LastName = "LastName23",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("48b5ff0d-da5a-4a9d-b58e-5a63cdc7ed3f"),
                            Age = "10",
                            Email = "Email24@gmail.com",
                            FirstName = "FirstName24",
                            IsDeleted = false,
                            LastName = "LastName24",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("35fc2031-417f-4531-aa20-7dfa3d4d1e34"),
                            Age = "10",
                            Email = "Email25@gmail.com",
                            FirstName = "FirstName25",
                            IsDeleted = false,
                            LastName = "LastName25",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("1706e07e-b7cf-4c99-8294-14c3e9b95894"),
                            Age = "10",
                            Email = "Email26@gmail.com",
                            FirstName = "FirstName26",
                            IsDeleted = false,
                            LastName = "LastName26",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("bdf0ec18-1f43-4d28-91ba-5a33f01225bb"),
                            Age = "10",
                            Email = "Email27@gmail.com",
                            FirstName = "FirstName27",
                            IsDeleted = false,
                            LastName = "LastName27",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("0bcc5798-8b74-460b-9c02-0dc2aee7ad5d"),
                            Age = "10",
                            Email = "Email28@gmail.com",
                            FirstName = "FirstName28",
                            IsDeleted = false,
                            LastName = "LastName28",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("78bb8a2e-6e10-4571-9c82-99e2f3c7854b"),
                            Age = "10",
                            Email = "Email29@gmail.com",
                            FirstName = "FirstName29",
                            IsDeleted = false,
                            LastName = "LastName29",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("be82c598-d203-4884-a3d3-ccc116a17dd9"),
                            Age = "10",
                            Email = "Email30@gmail.com",
                            FirstName = "FirstName30",
                            IsDeleted = false,
                            LastName = "LastName30",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("6e63b985-9ad7-4dcb-9c70-aec285b8148b"),
                            Age = "10",
                            Email = "Email31@gmail.com",
                            FirstName = "FirstName31",
                            IsDeleted = false,
                            LastName = "LastName31",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("883b3a09-c196-415e-90e1-5ad8b27aa0c3"),
                            Age = "10",
                            Email = "Email32@gmail.com",
                            FirstName = "FirstName32",
                            IsDeleted = false,
                            LastName = "LastName32",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("3cb84481-3f13-41f5-b8d9-e1eecc74f35c"),
                            Age = "10",
                            Email = "Email33@gmail.com",
                            FirstName = "FirstName33",
                            IsDeleted = false,
                            LastName = "LastName33",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("d7ad36a7-e2bb-4d8f-9bf3-c4ef7de1d729"),
                            Age = "10",
                            Email = "Email34@gmail.com",
                            FirstName = "FirstName34",
                            IsDeleted = false,
                            LastName = "LastName34",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("36dfa8d5-e585-49c7-af9e-7a25cb8b8172"),
                            Age = "10",
                            Email = "Email35@gmail.com",
                            FirstName = "FirstName35",
                            IsDeleted = false,
                            LastName = "LastName35",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("4f703f48-8058-4717-be75-c00b009b7d1a"),
                            Age = "10",
                            Email = "Email36@gmail.com",
                            FirstName = "FirstName36",
                            IsDeleted = false,
                            LastName = "LastName36",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("3d11886c-f192-45b1-8ca2-d3cc40711ed9"),
                            Age = "10",
                            Email = "Email37@gmail.com",
                            FirstName = "FirstName37",
                            IsDeleted = false,
                            LastName = "LastName37",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("3e239b25-6ee1-4c54-9caf-96d538d8d80b"),
                            Age = "10",
                            Email = "Email38@gmail.com",
                            FirstName = "FirstName38",
                            IsDeleted = false,
                            LastName = "LastName38",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("e08a578e-261f-4682-923c-e0931cfd6e47"),
                            Age = "10",
                            Email = "Email39@gmail.com",
                            FirstName = "FirstName39",
                            IsDeleted = false,
                            LastName = "LastName39",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("e2418b47-f1ca-4903-bdeb-a729d63decf2"),
                            Age = "10",
                            Email = "Email40@gmail.com",
                            FirstName = "FirstName40",
                            IsDeleted = false,
                            LastName = "LastName40",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("f0ba932e-3dcf-4c04-a958-fdb8e73d8742"),
                            Age = "10",
                            Email = "Email41@gmail.com",
                            FirstName = "FirstName41",
                            IsDeleted = false,
                            LastName = "LastName41",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("4207d355-9a86-4465-a6cc-69df00c2d38b"),
                            Age = "10",
                            Email = "Email42@gmail.com",
                            FirstName = "FirstName42",
                            IsDeleted = false,
                            LastName = "LastName42",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("1befd3cd-6bec-41e4-8c5d-c1c774ca37b4"),
                            Age = "10",
                            Email = "Email43@gmail.com",
                            FirstName = "FirstName43",
                            IsDeleted = false,
                            LastName = "LastName43",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("2a9c3007-6d6e-4f67-bc6b-dfd2cf9f7b1f"),
                            Age = "10",
                            Email = "Email44@gmail.com",
                            FirstName = "FirstName44",
                            IsDeleted = false,
                            LastName = "LastName44",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("cae35a44-164c-4262-a1bd-83a57b5d95f1"),
                            Age = "10",
                            Email = "Email45@gmail.com",
                            FirstName = "FirstName45",
                            IsDeleted = false,
                            LastName = "LastName45",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("7c083b13-be58-4fca-ad1f-ef7d309e4e1c"),
                            Age = "10",
                            Email = "Email46@gmail.com",
                            FirstName = "FirstName46",
                            IsDeleted = false,
                            LastName = "LastName46",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("b4bfac18-f670-4097-af32-9d9f30cb45ff"),
                            Age = "10",
                            Email = "Email47@gmail.com",
                            FirstName = "FirstName47",
                            IsDeleted = false,
                            LastName = "LastName47",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("80eb0192-57aa-44e6-a23c-900ca5588c9a"),
                            Age = "10",
                            Email = "Email48@gmail.com",
                            FirstName = "FirstName48",
                            IsDeleted = false,
                            LastName = "LastName48",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("e1aadaf9-937c-4a2a-bd3b-617033b11af4"),
                            Age = "10",
                            Email = "Email49@gmail.com",
                            FirstName = "FirstName49",
                            IsDeleted = false,
                            LastName = "LastName49",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("70f896c6-3f26-48f1-901a-f08011338d56"),
                            Age = "10",
                            Email = "Email50@gmail.com",
                            FirstName = "FirstName50",
                            IsDeleted = false,
                            LastName = "LastName50",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("e7c41d29-bce6-433b-bcd5-7423af33dc96"),
                            Age = "10",
                            Email = "Email51@gmail.com",
                            FirstName = "FirstName51",
                            IsDeleted = false,
                            LastName = "LastName51",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("2c427b6e-cfa7-4b90-9344-bc52c9bb450e"),
                            Age = "10",
                            Email = "Email52@gmail.com",
                            FirstName = "FirstName52",
                            IsDeleted = false,
                            LastName = "LastName52",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("32b04dc1-6c43-4f83-bb4d-e64dd00ae452"),
                            Age = "10",
                            Email = "Email53@gmail.com",
                            FirstName = "FirstName53",
                            IsDeleted = false,
                            LastName = "LastName53",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("199b4d01-573f-4eb3-aedb-6bd895552ce4"),
                            Age = "10",
                            Email = "Email54@gmail.com",
                            FirstName = "FirstName54",
                            IsDeleted = false,
                            LastName = "LastName54",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("a8e77aaa-a916-49aa-8165-9867c6ef17a1"),
                            Age = "10",
                            Email = "Email55@gmail.com",
                            FirstName = "FirstName55",
                            IsDeleted = false,
                            LastName = "LastName55",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("5e332eca-d86f-4e5a-9269-225cfd6832c1"),
                            Age = "10",
                            Email = "Email56@gmail.com",
                            FirstName = "FirstName56",
                            IsDeleted = false,
                            LastName = "LastName56",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("c7ce0945-8e8d-4d81-a6f6-8b993ec924ec"),
                            Age = "10",
                            Email = "Email57@gmail.com",
                            FirstName = "FirstName57",
                            IsDeleted = false,
                            LastName = "LastName57",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("78bf1856-ede8-40e7-a975-db3bbaccf77a"),
                            Age = "10",
                            Email = "Email58@gmail.com",
                            FirstName = "FirstName58",
                            IsDeleted = false,
                            LastName = "LastName58",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("e28e883b-c277-4a3f-a29d-eb12d2a25824"),
                            Age = "10",
                            Email = "Email59@gmail.com",
                            FirstName = "FirstName59",
                            IsDeleted = false,
                            LastName = "LastName59",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("76fe7e29-c32f-4e3d-a06c-a2a3571611a9"),
                            Age = "10",
                            Email = "Email60@gmail.com",
                            FirstName = "FirstName60",
                            IsDeleted = false,
                            LastName = "LastName60",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("bf026c9f-b552-4d53-a802-7e77f439d0eb"),
                            Age = "10",
                            Email = "Email61@gmail.com",
                            FirstName = "FirstName61",
                            IsDeleted = false,
                            LastName = "LastName61",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("8cc374e4-f029-479f-9220-c72012ee9582"),
                            Age = "10",
                            Email = "Email62@gmail.com",
                            FirstName = "FirstName62",
                            IsDeleted = false,
                            LastName = "LastName62",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("6435fbbb-b240-4349-92d0-796681a347b0"),
                            Age = "10",
                            Email = "Email63@gmail.com",
                            FirstName = "FirstName63",
                            IsDeleted = false,
                            LastName = "LastName63",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("dfb85c8c-fe4f-4d71-aeeb-f8df0159d524"),
                            Age = "10",
                            Email = "Email64@gmail.com",
                            FirstName = "FirstName64",
                            IsDeleted = false,
                            LastName = "LastName64",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("6bf8e044-4670-4749-adff-b24106f75b1f"),
                            Age = "10",
                            Email = "Email65@gmail.com",
                            FirstName = "FirstName65",
                            IsDeleted = false,
                            LastName = "LastName65",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("cecb5265-1afe-4c52-8955-bfc6110f209a"),
                            Age = "10",
                            Email = "Email66@gmail.com",
                            FirstName = "FirstName66",
                            IsDeleted = false,
                            LastName = "LastName66",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("de01b024-7626-470f-b73b-3d58a82ebac9"),
                            Age = "10",
                            Email = "Email67@gmail.com",
                            FirstName = "FirstName67",
                            IsDeleted = false,
                            LastName = "LastName67",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("76f55a5a-d5db-42d0-9203-7f88abaaf670"),
                            Age = "10",
                            Email = "Email68@gmail.com",
                            FirstName = "FirstName68",
                            IsDeleted = false,
                            LastName = "LastName68",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("ae595186-a58f-42f0-98a6-0b291449bec1"),
                            Age = "10",
                            Email = "Email69@gmail.com",
                            FirstName = "FirstName69",
                            IsDeleted = false,
                            LastName = "LastName69",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("b3eb6701-ffcf-4aac-8d68-f39658bd16e4"),
                            Age = "10",
                            Email = "Email70@gmail.com",
                            FirstName = "FirstName70",
                            IsDeleted = false,
                            LastName = "LastName70",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("9af2bb54-90de-43fe-94d0-414f4ddb7d7d"),
                            Age = "10",
                            Email = "Email71@gmail.com",
                            FirstName = "FirstName71",
                            IsDeleted = false,
                            LastName = "LastName71",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("893b836c-5859-4c04-afc1-121768edcd13"),
                            Age = "10",
                            Email = "Email72@gmail.com",
                            FirstName = "FirstName72",
                            IsDeleted = false,
                            LastName = "LastName72",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("c5a2312c-5617-4277-9aef-e4ff1027b459"),
                            Age = "10",
                            Email = "Email73@gmail.com",
                            FirstName = "FirstName73",
                            IsDeleted = false,
                            LastName = "LastName73",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("ae32ebec-076b-473e-ba34-c1f4f3db0f16"),
                            Age = "10",
                            Email = "Email74@gmail.com",
                            FirstName = "FirstName74",
                            IsDeleted = false,
                            LastName = "LastName74",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("15351b10-a317-4939-9d08-99d60b39b11d"),
                            Age = "10",
                            Email = "Email75@gmail.com",
                            FirstName = "FirstName75",
                            IsDeleted = false,
                            LastName = "LastName75",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("e3baeb8e-036e-4e3a-999e-b328e08e7183"),
                            Age = "10",
                            Email = "Email76@gmail.com",
                            FirstName = "FirstName76",
                            IsDeleted = false,
                            LastName = "LastName76",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("dc691b69-4303-4c55-b0aa-3d9cd5ea38cf"),
                            Age = "10",
                            Email = "Email77@gmail.com",
                            FirstName = "FirstName77",
                            IsDeleted = false,
                            LastName = "LastName77",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("9311ad48-e21b-471a-8d8a-3aeee5ac3495"),
                            Age = "10",
                            Email = "Email78@gmail.com",
                            FirstName = "FirstName78",
                            IsDeleted = false,
                            LastName = "LastName78",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("abd93f44-b421-4efa-a2c9-31bd6befbf5e"),
                            Age = "10",
                            Email = "Email79@gmail.com",
                            FirstName = "FirstName79",
                            IsDeleted = false,
                            LastName = "LastName79",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("b99ba7d6-ac28-4556-bc2c-dbb681aefe20"),
                            Age = "10",
                            Email = "Email80@gmail.com",
                            FirstName = "FirstName80",
                            IsDeleted = false,
                            LastName = "LastName80",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("5888af6e-fb6f-4598-92ea-569a6a8355d6"),
                            Age = "10",
                            Email = "Email81@gmail.com",
                            FirstName = "FirstName81",
                            IsDeleted = false,
                            LastName = "LastName81",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("1a8f6cd3-8dcd-496e-8795-7ebd05074162"),
                            Age = "10",
                            Email = "Email82@gmail.com",
                            FirstName = "FirstName82",
                            IsDeleted = false,
                            LastName = "LastName82",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("fac0c029-8f61-4982-ae0d-5a8605664c29"),
                            Age = "10",
                            Email = "Email83@gmail.com",
                            FirstName = "FirstName83",
                            IsDeleted = false,
                            LastName = "LastName83",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("dea10dfc-4ce7-4db1-9daf-1fa7b1d74a58"),
                            Age = "10",
                            Email = "Email84@gmail.com",
                            FirstName = "FirstName84",
                            IsDeleted = false,
                            LastName = "LastName84",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("3ba43a0f-e9f9-44be-a2b4-5ec0bc5ca946"),
                            Age = "10",
                            Email = "Email85@gmail.com",
                            FirstName = "FirstName85",
                            IsDeleted = false,
                            LastName = "LastName85",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("b6ed2adf-e135-45e8-8413-d5edc5d1c76e"),
                            Age = "10",
                            Email = "Email86@gmail.com",
                            FirstName = "FirstName86",
                            IsDeleted = false,
                            LastName = "LastName86",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("51540255-b7a3-4e61-a6f2-9e74e92eb5e7"),
                            Age = "10",
                            Email = "Email87@gmail.com",
                            FirstName = "FirstName87",
                            IsDeleted = false,
                            LastName = "LastName87",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("2eac6858-9d2d-43e9-a6cc-717676a23b70"),
                            Age = "10",
                            Email = "Email88@gmail.com",
                            FirstName = "FirstName88",
                            IsDeleted = false,
                            LastName = "LastName88",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("348fa082-e384-4025-882c-143357bd1556"),
                            Age = "10",
                            Email = "Email89@gmail.com",
                            FirstName = "FirstName89",
                            IsDeleted = false,
                            LastName = "LastName89",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("703ffab8-8ae6-48db-a118-56bb92be5162"),
                            Age = "10",
                            Email = "Email90@gmail.com",
                            FirstName = "FirstName90",
                            IsDeleted = false,
                            LastName = "LastName90",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("c58765c3-66d6-4fa5-b41a-5e8f2cd4317f"),
                            Age = "10",
                            Email = "Email91@gmail.com",
                            FirstName = "FirstName91",
                            IsDeleted = false,
                            LastName = "LastName91",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("8b7fa11b-a34c-441c-a50c-7ce1c0468576"),
                            Age = "10",
                            Email = "Email92@gmail.com",
                            FirstName = "FirstName92",
                            IsDeleted = false,
                            LastName = "LastName92",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("f58e9bdb-4f48-4118-a387-cbfbbf3a0c79"),
                            Age = "10",
                            Email = "Email93@gmail.com",
                            FirstName = "FirstName93",
                            IsDeleted = false,
                            LastName = "LastName93",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("9d96bc65-f153-465f-965d-6469ee91ae3b"),
                            Age = "10",
                            Email = "Email94@gmail.com",
                            FirstName = "FirstName94",
                            IsDeleted = false,
                            LastName = "LastName94",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("93dcdf10-5f9a-4c7b-baba-1b6be1dd4e2d"),
                            Age = "10",
                            Email = "Email95@gmail.com",
                            FirstName = "FirstName95",
                            IsDeleted = false,
                            LastName = "LastName95",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("58e180c7-9a3a-40ab-9f8b-df7516e05c03"),
                            Age = "10",
                            Email = "Email96@gmail.com",
                            FirstName = "FirstName96",
                            IsDeleted = false,
                            LastName = "LastName96",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("34c0fad2-6e96-4eb0-b620-1821b31eaff6"),
                            Age = "10",
                            Email = "Email97@gmail.com",
                            FirstName = "FirstName97",
                            IsDeleted = false,
                            LastName = "LastName97",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("1768e4a8-dd3a-4653-b3dc-5a417c76ed2d"),
                            Age = "10",
                            Email = "Email98@gmail.com",
                            FirstName = "FirstName98",
                            IsDeleted = false,
                            LastName = "LastName98",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("5555708e-aadd-42ff-aefc-be52cf7b8593"),
                            Age = "10",
                            Email = "Email99@gmail.com",
                            FirstName = "FirstName99",
                            IsDeleted = false,
                            LastName = "LastName99",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        });
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.ApplyRequest", b =>
                {
                    b.HasOne("DOTNET_hocmienphi.repository.entity.User", "User")
                        .WithMany("ApplyRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Category", b =>
                {
                    b.HasOne("DOTNET_hocmienphi.repository.entity.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Meeting", b =>
                {
                    b.HasOne("DOTNET_hocmienphi.repository.entity.User", "User")
                        .WithMany("Meetings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Mentor", b =>
                {
                    b.HasOne("DOTNET_hocmienphi.repository.entity.User", "User")
                        .WithOne("Mentor")
                        .HasForeignKey("DOTNET_hocmienphi.repository.entity.Mentor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.MentorCategory", b =>
                {
                    b.HasOne("DOTNET_hocmienphi.repository.entity.Category", "Category")
                        .WithMany("MentorCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DOTNET_hocmienphi.repository.entity.Mentor", "Mentor")
                        .WithMany("MentorCategories")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("MentorCategories");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Mentor", b =>
                {
                    b.Navigation("MentorCategories");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.User", b =>
                {
                    b.Navigation("ApplyRequests");

                    b.Navigation("Meetings");

                    b.Navigation("Mentor");
                });
#pragma warning restore 612, 618
        }
    }
}
