// <auto-generated />
using System;
using DOTNET_hocmienphi.repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DOTNET_hocmienphi.repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260619081916_MeetingConfiguration")]
    partial class MeetingConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Meeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bc77c420-61fb-4de5-8fa2-4481e2d5be98"),
                            Age = "10",
                            Email = "Email0@gmail.com",
                            FirstName = "FirstName0",
                            IsDeleted = false,
                            LastName = "LastName0",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("3dcf8f48-b7c0-455a-b944-fccb49e24272"),
                            Age = "10",
                            Email = "Email1@gmail.com",
                            FirstName = "FirstName1",
                            IsDeleted = false,
                            LastName = "LastName1",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("65a0b3e4-65cb-490c-b10a-d75ec49609b8"),
                            Age = "10",
                            Email = "Email2@gmail.com",
                            FirstName = "FirstName2",
                            IsDeleted = false,
                            LastName = "LastName2",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("6702a71b-d352-4624-b2bb-c8d0bfd2872b"),
                            Age = "10",
                            Email = "Email3@gmail.com",
                            FirstName = "FirstName3",
                            IsDeleted = false,
                            LastName = "LastName3",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("5ef7b9b0-08b2-4b95-b27b-5942bfdecc8a"),
                            Age = "10",
                            Email = "Email4@gmail.com",
                            FirstName = "FirstName4",
                            IsDeleted = false,
                            LastName = "LastName4",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("88ef378a-1e6c-4c74-8f42-83518104dbe1"),
                            Age = "10",
                            Email = "Email5@gmail.com",
                            FirstName = "FirstName5",
                            IsDeleted = false,
                            LastName = "LastName5",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("50ee3d02-ef1f-49ac-9331-ed1833c2ce07"),
                            Age = "10",
                            Email = "Email6@gmail.com",
                            FirstName = "FirstName6",
                            IsDeleted = false,
                            LastName = "LastName6",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("f17eaf07-e7e4-493a-954d-19dc63b3c9ad"),
                            Age = "10",
                            Email = "Email7@gmail.com",
                            FirstName = "FirstName7",
                            IsDeleted = false,
                            LastName = "LastName7",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("4be76f75-3ee0-4a9c-81fe-b37d99c31cb7"),
                            Age = "10",
                            Email = "Email8@gmail.com",
                            FirstName = "FirstName8",
                            IsDeleted = false,
                            LastName = "LastName8",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("3a740fe1-d92f-4846-aa01-53b72917d818"),
                            Age = "10",
                            Email = "Email9@gmail.com",
                            FirstName = "FirstName9",
                            IsDeleted = false,
                            LastName = "LastName9",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("fa92eb63-1dfc-4077-8510-253fb57619f9"),
                            Age = "10",
                            Email = "Email10@gmail.com",
                            FirstName = "FirstName10",
                            IsDeleted = false,
                            LastName = "LastName10",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("9f4949d4-e10b-4d0f-8591-8a315bf2273c"),
                            Age = "10",
                            Email = "Email11@gmail.com",
                            FirstName = "FirstName11",
                            IsDeleted = false,
                            LastName = "LastName11",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("1da90569-c05f-45e9-9b99-f4600a53a66b"),
                            Age = "10",
                            Email = "Email12@gmail.com",
                            FirstName = "FirstName12",
                            IsDeleted = false,
                            LastName = "LastName12",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("deb7ab49-9a4b-4756-8ea4-3a68b329bec0"),
                            Age = "10",
                            Email = "Email13@gmail.com",
                            FirstName = "FirstName13",
                            IsDeleted = false,
                            LastName = "LastName13",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("70db1c40-1eeb-48e0-9092-8ca3db84159f"),
                            Age = "10",
                            Email = "Email14@gmail.com",
                            FirstName = "FirstName14",
                            IsDeleted = false,
                            LastName = "LastName14",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("e66020b5-0604-4d45-9a7c-693f20cfd7b0"),
                            Age = "10",
                            Email = "Email15@gmail.com",
                            FirstName = "FirstName15",
                            IsDeleted = false,
                            LastName = "LastName15",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("8d88f6cc-6fd9-405e-8798-77f638b87e20"),
                            Age = "10",
                            Email = "Email16@gmail.com",
                            FirstName = "FirstName16",
                            IsDeleted = false,
                            LastName = "LastName16",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("42daffba-a4c2-471b-aa1c-c8f649b8f115"),
                            Age = "10",
                            Email = "Email17@gmail.com",
                            FirstName = "FirstName17",
                            IsDeleted = false,
                            LastName = "LastName17",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("b652d514-8745-4cd7-87d1-522a7e09db2e"),
                            Age = "10",
                            Email = "Email18@gmail.com",
                            FirstName = "FirstName18",
                            IsDeleted = false,
                            LastName = "LastName18",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("5081fc31-537e-449b-8541-8a48ad5e176a"),
                            Age = "10",
                            Email = "Email19@gmail.com",
                            FirstName = "FirstName19",
                            IsDeleted = false,
                            LastName = "LastName19",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("0c6f1c4d-25d8-42d9-a4cf-2329196c71f9"),
                            Age = "10",
                            Email = "Email20@gmail.com",
                            FirstName = "FirstName20",
                            IsDeleted = false,
                            LastName = "LastName20",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("9584ef93-41c7-4468-9117-fe22e1ed1092"),
                            Age = "10",
                            Email = "Email21@gmail.com",
                            FirstName = "FirstName21",
                            IsDeleted = false,
                            LastName = "LastName21",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("666e34d3-f9b5-4f7a-979f-4cddde1a179d"),
                            Age = "10",
                            Email = "Email22@gmail.com",
                            FirstName = "FirstName22",
                            IsDeleted = false,
                            LastName = "LastName22",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("41a6aa81-11f5-4763-bc35-3237dfd774b8"),
                            Age = "10",
                            Email = "Email23@gmail.com",
                            FirstName = "FirstName23",
                            IsDeleted = false,
                            LastName = "LastName23",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("94cb9541-fced-4dc1-ba3c-c53876ddf905"),
                            Age = "10",
                            Email = "Email24@gmail.com",
                            FirstName = "FirstName24",
                            IsDeleted = false,
                            LastName = "LastName24",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("664acfa4-8630-4d9f-8292-fe991a4da1e9"),
                            Age = "10",
                            Email = "Email25@gmail.com",
                            FirstName = "FirstName25",
                            IsDeleted = false,
                            LastName = "LastName25",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("2980d81f-d8d2-4d44-a19b-6a4e5a20791c"),
                            Age = "10",
                            Email = "Email26@gmail.com",
                            FirstName = "FirstName26",
                            IsDeleted = false,
                            LastName = "LastName26",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("25abf871-9d58-45d2-a6be-bed5a7fd8c9c"),
                            Age = "10",
                            Email = "Email27@gmail.com",
                            FirstName = "FirstName27",
                            IsDeleted = false,
                            LastName = "LastName27",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("02d99124-625b-4c19-a1e1-5e7c68dd0931"),
                            Age = "10",
                            Email = "Email28@gmail.com",
                            FirstName = "FirstName28",
                            IsDeleted = false,
                            LastName = "LastName28",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("a43c05f6-8b84-4ffb-8930-f45a10a5cb0a"),
                            Age = "10",
                            Email = "Email29@gmail.com",
                            FirstName = "FirstName29",
                            IsDeleted = false,
                            LastName = "LastName29",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("ecd0e615-5588-466e-bce5-2d76861e213d"),
                            Age = "10",
                            Email = "Email30@gmail.com",
                            FirstName = "FirstName30",
                            IsDeleted = false,
                            LastName = "LastName30",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("bb25545e-e820-47bd-b63d-212d77d738b0"),
                            Age = "10",
                            Email = "Email31@gmail.com",
                            FirstName = "FirstName31",
                            IsDeleted = false,
                            LastName = "LastName31",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("33a344ed-d8bb-43e9-96f9-1b5e8f9ad12b"),
                            Age = "10",
                            Email = "Email32@gmail.com",
                            FirstName = "FirstName32",
                            IsDeleted = false,
                            LastName = "LastName32",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("940a63cd-0100-441d-9e8e-40a17b041257"),
                            Age = "10",
                            Email = "Email33@gmail.com",
                            FirstName = "FirstName33",
                            IsDeleted = false,
                            LastName = "LastName33",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("390353e3-d850-489f-9f90-78b161616c41"),
                            Age = "10",
                            Email = "Email34@gmail.com",
                            FirstName = "FirstName34",
                            IsDeleted = false,
                            LastName = "LastName34",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("c2fdf3db-7746-4507-8630-1dcffa2568ef"),
                            Age = "10",
                            Email = "Email35@gmail.com",
                            FirstName = "FirstName35",
                            IsDeleted = false,
                            LastName = "LastName35",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("5346ff80-c21e-4331-aeff-d90a995856ac"),
                            Age = "10",
                            Email = "Email36@gmail.com",
                            FirstName = "FirstName36",
                            IsDeleted = false,
                            LastName = "LastName36",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("b284abd0-affe-490b-b3b3-9d79a3be8135"),
                            Age = "10",
                            Email = "Email37@gmail.com",
                            FirstName = "FirstName37",
                            IsDeleted = false,
                            LastName = "LastName37",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("b99abb8a-e596-41bd-bb47-096cf4395b27"),
                            Age = "10",
                            Email = "Email38@gmail.com",
                            FirstName = "FirstName38",
                            IsDeleted = false,
                            LastName = "LastName38",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("1ece4746-3c02-40f9-8051-8cad6704e9d1"),
                            Age = "10",
                            Email = "Email39@gmail.com",
                            FirstName = "FirstName39",
                            IsDeleted = false,
                            LastName = "LastName39",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("e57980f7-f2e2-4e07-9e4d-a4daacdffc3b"),
                            Age = "10",
                            Email = "Email40@gmail.com",
                            FirstName = "FirstName40",
                            IsDeleted = false,
                            LastName = "LastName40",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("12157c6e-fa17-4aae-a6ca-420248a05b37"),
                            Age = "10",
                            Email = "Email41@gmail.com",
                            FirstName = "FirstName41",
                            IsDeleted = false,
                            LastName = "LastName41",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("37983300-bc4c-4f5b-88c5-f5a0d6c6b1d3"),
                            Age = "10",
                            Email = "Email42@gmail.com",
                            FirstName = "FirstName42",
                            IsDeleted = false,
                            LastName = "LastName42",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("d834c5e3-3a82-4aa7-a907-cec6ee6b9cce"),
                            Age = "10",
                            Email = "Email43@gmail.com",
                            FirstName = "FirstName43",
                            IsDeleted = false,
                            LastName = "LastName43",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("4c9c85c3-a6c3-4b7b-b8b5-15a09d09899d"),
                            Age = "10",
                            Email = "Email44@gmail.com",
                            FirstName = "FirstName44",
                            IsDeleted = false,
                            LastName = "LastName44",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("b96a4fd4-1a37-4a0c-8a3e-d1beb989fe70"),
                            Age = "10",
                            Email = "Email45@gmail.com",
                            FirstName = "FirstName45",
                            IsDeleted = false,
                            LastName = "LastName45",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("8704bff7-fd2e-4b64-bd4c-756628b5d592"),
                            Age = "10",
                            Email = "Email46@gmail.com",
                            FirstName = "FirstName46",
                            IsDeleted = false,
                            LastName = "LastName46",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("2b207ccc-b6ef-41b9-9f7a-b028e9ef9d11"),
                            Age = "10",
                            Email = "Email47@gmail.com",
                            FirstName = "FirstName47",
                            IsDeleted = false,
                            LastName = "LastName47",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("286ae138-ec65-4c84-9c6f-e3c25dfde814"),
                            Age = "10",
                            Email = "Email48@gmail.com",
                            FirstName = "FirstName48",
                            IsDeleted = false,
                            LastName = "LastName48",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("a511cbcb-4488-4d40-8b83-9bc38a30afbe"),
                            Age = "10",
                            Email = "Email49@gmail.com",
                            FirstName = "FirstName49",
                            IsDeleted = false,
                            LastName = "LastName49",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("a53dc8a9-a04d-44b4-8cdb-9bbd62fa54d0"),
                            Age = "10",
                            Email = "Email50@gmail.com",
                            FirstName = "FirstName50",
                            IsDeleted = false,
                            LastName = "LastName50",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("9c7ce40b-e5a5-4cee-a854-ab0e2155c20b"),
                            Age = "10",
                            Email = "Email51@gmail.com",
                            FirstName = "FirstName51",
                            IsDeleted = false,
                            LastName = "LastName51",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("7809525f-1d6b-4bee-82e5-bddb68138d7e"),
                            Age = "10",
                            Email = "Email52@gmail.com",
                            FirstName = "FirstName52",
                            IsDeleted = false,
                            LastName = "LastName52",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("fc41b310-04bf-42b3-b72b-c5257236cd4a"),
                            Age = "10",
                            Email = "Email53@gmail.com",
                            FirstName = "FirstName53",
                            IsDeleted = false,
                            LastName = "LastName53",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("9355f3b7-5ebb-4256-acaa-fde79a8c2f12"),
                            Age = "10",
                            Email = "Email54@gmail.com",
                            FirstName = "FirstName54",
                            IsDeleted = false,
                            LastName = "LastName54",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("1a4ca1fa-f47c-44be-a6d4-05c9cbf0c356"),
                            Age = "10",
                            Email = "Email55@gmail.com",
                            FirstName = "FirstName55",
                            IsDeleted = false,
                            LastName = "LastName55",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("db07aa97-81cb-48d0-b0f0-9822c280c34f"),
                            Age = "10",
                            Email = "Email56@gmail.com",
                            FirstName = "FirstName56",
                            IsDeleted = false,
                            LastName = "LastName56",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("10a70254-bdf0-4a7d-ab8c-fbd11314f1bc"),
                            Age = "10",
                            Email = "Email57@gmail.com",
                            FirstName = "FirstName57",
                            IsDeleted = false,
                            LastName = "LastName57",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("cd0a0d5e-d883-4ad2-b146-d5cfa653bee1"),
                            Age = "10",
                            Email = "Email58@gmail.com",
                            FirstName = "FirstName58",
                            IsDeleted = false,
                            LastName = "LastName58",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("9020b07f-8116-4073-907e-b6a19d2b61e7"),
                            Age = "10",
                            Email = "Email59@gmail.com",
                            FirstName = "FirstName59",
                            IsDeleted = false,
                            LastName = "LastName59",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("ed245216-141e-4821-89b8-eabfb2134531"),
                            Age = "10",
                            Email = "Email60@gmail.com",
                            FirstName = "FirstName60",
                            IsDeleted = false,
                            LastName = "LastName60",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("6c6f1f15-4ae1-4311-b4b7-75f9f034d9c5"),
                            Age = "10",
                            Email = "Email61@gmail.com",
                            FirstName = "FirstName61",
                            IsDeleted = false,
                            LastName = "LastName61",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("ca65d9c1-f1a4-40bc-8b15-9514f5d0a690"),
                            Age = "10",
                            Email = "Email62@gmail.com",
                            FirstName = "FirstName62",
                            IsDeleted = false,
                            LastName = "LastName62",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("79f3d1c1-7786-48ef-8ebe-9c35549b768d"),
                            Age = "10",
                            Email = "Email63@gmail.com",
                            FirstName = "FirstName63",
                            IsDeleted = false,
                            LastName = "LastName63",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("a39646bb-b10a-4aa9-a095-9d8e8512edc8"),
                            Age = "10",
                            Email = "Email64@gmail.com",
                            FirstName = "FirstName64",
                            IsDeleted = false,
                            LastName = "LastName64",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("4f4c3566-8763-4e75-950e-795972b87b53"),
                            Age = "10",
                            Email = "Email65@gmail.com",
                            FirstName = "FirstName65",
                            IsDeleted = false,
                            LastName = "LastName65",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("6125d47a-3d0b-4462-ab3e-2d4e66e52ea3"),
                            Age = "10",
                            Email = "Email66@gmail.com",
                            FirstName = "FirstName66",
                            IsDeleted = false,
                            LastName = "LastName66",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("d3045b8b-5d3b-408e-aa97-fb53b9e34f55"),
                            Age = "10",
                            Email = "Email67@gmail.com",
                            FirstName = "FirstName67",
                            IsDeleted = false,
                            LastName = "LastName67",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("9336bc86-2f14-4353-9235-642f178d9403"),
                            Age = "10",
                            Email = "Email68@gmail.com",
                            FirstName = "FirstName68",
                            IsDeleted = false,
                            LastName = "LastName68",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("ecf9104d-cbcf-40a6-b457-736372a479be"),
                            Age = "10",
                            Email = "Email69@gmail.com",
                            FirstName = "FirstName69",
                            IsDeleted = false,
                            LastName = "LastName69",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("baa623c1-8a81-4def-a6b6-4b9b7546b57f"),
                            Age = "10",
                            Email = "Email70@gmail.com",
                            FirstName = "FirstName70",
                            IsDeleted = false,
                            LastName = "LastName70",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("f7b95114-0c63-40d0-94e7-80df90b8b098"),
                            Age = "10",
                            Email = "Email71@gmail.com",
                            FirstName = "FirstName71",
                            IsDeleted = false,
                            LastName = "LastName71",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("396ff2b9-26bb-4408-82a2-902731a21e37"),
                            Age = "10",
                            Email = "Email72@gmail.com",
                            FirstName = "FirstName72",
                            IsDeleted = false,
                            LastName = "LastName72",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("fec449c4-aaef-42de-8436-75024d001ca0"),
                            Age = "10",
                            Email = "Email73@gmail.com",
                            FirstName = "FirstName73",
                            IsDeleted = false,
                            LastName = "LastName73",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("bceb4660-ec26-488d-a882-6966175e7082"),
                            Age = "10",
                            Email = "Email74@gmail.com",
                            FirstName = "FirstName74",
                            IsDeleted = false,
                            LastName = "LastName74",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("1c0fe1f5-c708-4742-b1af-b060f3992670"),
                            Age = "10",
                            Email = "Email75@gmail.com",
                            FirstName = "FirstName75",
                            IsDeleted = false,
                            LastName = "LastName75",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("ad53c2b2-8da8-433c-93c3-c6eaa8c29575"),
                            Age = "10",
                            Email = "Email76@gmail.com",
                            FirstName = "FirstName76",
                            IsDeleted = false,
                            LastName = "LastName76",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("133858ef-0fe5-4c6a-a50a-974b1540fcff"),
                            Age = "10",
                            Email = "Email77@gmail.com",
                            FirstName = "FirstName77",
                            IsDeleted = false,
                            LastName = "LastName77",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("78665603-1e1b-41a0-bf34-8cb80ff475bb"),
                            Age = "10",
                            Email = "Email78@gmail.com",
                            FirstName = "FirstName78",
                            IsDeleted = false,
                            LastName = "LastName78",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("6d9635aa-e0a1-460a-a555-f7bfbcc8d51c"),
                            Age = "10",
                            Email = "Email79@gmail.com",
                            FirstName = "FirstName79",
                            IsDeleted = false,
                            LastName = "LastName79",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("1741a198-499d-44b1-9a18-d537d2095947"),
                            Age = "10",
                            Email = "Email80@gmail.com",
                            FirstName = "FirstName80",
                            IsDeleted = false,
                            LastName = "LastName80",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("5f36fd9b-70a2-4370-bf9e-cd65fe24e04d"),
                            Age = "10",
                            Email = "Email81@gmail.com",
                            FirstName = "FirstName81",
                            IsDeleted = false,
                            LastName = "LastName81",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("0666846a-def5-4cc8-a077-6583639a44d9"),
                            Age = "10",
                            Email = "Email82@gmail.com",
                            FirstName = "FirstName82",
                            IsDeleted = false,
                            LastName = "LastName82",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("a901d9fc-2863-402b-b801-1f8a1fcf55ff"),
                            Age = "10",
                            Email = "Email83@gmail.com",
                            FirstName = "FirstName83",
                            IsDeleted = false,
                            LastName = "LastName83",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("8da63c40-10b2-4520-93bb-975bd51c03f3"),
                            Age = "10",
                            Email = "Email84@gmail.com",
                            FirstName = "FirstName84",
                            IsDeleted = false,
                            LastName = "LastName84",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("2a8c98f0-7397-4b44-9d38-7fb6fdf4db06"),
                            Age = "10",
                            Email = "Email85@gmail.com",
                            FirstName = "FirstName85",
                            IsDeleted = false,
                            LastName = "LastName85",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("86d7d320-05d0-44af-a385-62e486b069a4"),
                            Age = "10",
                            Email = "Email86@gmail.com",
                            FirstName = "FirstName86",
                            IsDeleted = false,
                            LastName = "LastName86",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("8aea45aa-8a93-4a3b-9a70-2a65098fe1f0"),
                            Age = "10",
                            Email = "Email87@gmail.com",
                            FirstName = "FirstName87",
                            IsDeleted = false,
                            LastName = "LastName87",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("bbf220aa-41fa-428e-ad9f-6d04507791be"),
                            Age = "10",
                            Email = "Email88@gmail.com",
                            FirstName = "FirstName88",
                            IsDeleted = false,
                            LastName = "LastName88",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("379f1bb8-7866-4ec3-be24-c962fee55fd2"),
                            Age = "10",
                            Email = "Email89@gmail.com",
                            FirstName = "FirstName89",
                            IsDeleted = false,
                            LastName = "LastName89",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("aa63a555-cc64-407d-8a35-b174254655c2"),
                            Age = "10",
                            Email = "Email90@gmail.com",
                            FirstName = "FirstName90",
                            IsDeleted = false,
                            LastName = "LastName90",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("7b3849ed-2db3-4b6b-beed-5f246a9d8395"),
                            Age = "10",
                            Email = "Email91@gmail.com",
                            FirstName = "FirstName91",
                            IsDeleted = false,
                            LastName = "LastName91",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("1525a95c-29d3-4730-b47e-3724ce73fe05"),
                            Age = "10",
                            Email = "Email92@gmail.com",
                            FirstName = "FirstName92",
                            IsDeleted = false,
                            LastName = "LastName92",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("2b9fb8ca-0d64-4826-a64b-b7801bae6628"),
                            Age = "10",
                            Email = "Email93@gmail.com",
                            FirstName = "FirstName93",
                            IsDeleted = false,
                            LastName = "LastName93",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("f4c7012c-9fcb-4bf6-b4de-96218ed23454"),
                            Age = "10",
                            Email = "Email94@gmail.com",
                            FirstName = "FirstName94",
                            IsDeleted = false,
                            LastName = "LastName94",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("58f39452-e030-4663-b330-6876b0d8fe8b"),
                            Age = "10",
                            Email = "Email95@gmail.com",
                            FirstName = "FirstName95",
                            IsDeleted = false,
                            LastName = "LastName95",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("b5e6a695-2456-4be7-bdeb-f91a32f7b868"),
                            Age = "10",
                            Email = "Email96@gmail.com",
                            FirstName = "FirstName96",
                            IsDeleted = false,
                            LastName = "LastName96",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("9f0650c8-7729-4c20-aa20-5cb38fe3dfe9"),
                            Age = "10",
                            Email = "Email97@gmail.com",
                            FirstName = "FirstName97",
                            IsDeleted = false,
                            LastName = "LastName97",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("10efbd44-6f1e-4248-8eb5-78c46e0705b3"),
                            Age = "10",
                            Email = "Email98@gmail.com",
                            FirstName = "FirstName98",
                            IsDeleted = false,
                            LastName = "LastName98",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("e25e8a2f-a70c-4ac5-9a9e-4a9ccd3df7c4"),
                            Age = "10",
                            Email = "Email99@gmail.com",
                            FirstName = "FirstName99",
                            IsDeleted = false,
                            LastName = "LastName99",
                            Password = "123123",
                            Phone = "123123",
                            Role = "Student"
                        });
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Category", b =>
                {
                    b.HasOne("DOTNET_hocmienphi.repository.entity.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Meeting", b =>
                {
                    b.HasOne("DOTNET_hocmienphi.repository.entity.User", "User")
                        .WithMany("Meetings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.Category", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("DOTNET_hocmienphi.repository.entity.User", b =>
                {
                    b.Navigation("Meetings");
                });
#pragma warning restore 612, 618
        }
    }
}
